feat(Menu): add selectable classnames
alibaba-fusion/next pull request #2196
Opened 2020-09-21 11:14 UTC by csr632

我们这边对于可选择的menu（即带有✔️符号的menu），需要做一些样式覆盖，但是目前没有可靠选择器能够选中”可选择的menu“。

2020-09-21 11:16 UTC, youluna commented on src/menu/view/menu.jsx
> +            [`${prefix}menu-selectable-multiple`]: this.props.selectMode === 'multiple',
[`${prefix}menu-${selectMode}`]: selectMode,

2020-09-22 03:14 UTC, csr632 commented on src/input/group.jsx
> +        const before = addonBefore ? <span className={beforeCls}>{addonBefore}</span> : null;
被自动format改的

2020-09-24 11:37 UTC, youluna requested changes

2020-09-24 11:37 UTC, youluna commented on src/input/group.jsx
> +            [`${prefix}disabled`]: disabled,
目前Input.Group不支持disabled模式，如果要加这个API，不能只加className需要把功能一起加上
@bindoon Input.Group不支持disabled  单纯是之前没人提这个需求吗
![image](https://user-images.githubusercontent.com/10049465/94139313-06c2bb80-fe9c-11ea-9021-fcd0858eb9f5.png)

2020-09-24 11:37 UTC, youluna commented on src/menu/view/menu.jsx
> +            [`${prefix}menu-selectable-${selectMode}`]: selectMode,
是单选、多选样式要变化么，比如单选是圆圈，多选是对号

2020-09-24 11:37 UTC, youluna commented on src/table/base.jsx
> +                rowSelection,
这里有问题，把rowSelection 挑出来了，后面得塞回去，不然后面组件拿不到rowSelection参数

2020-09-24 13:55 UTC, youluna commented on src/input/group.jsx
> +            [`${prefix}disabled`]: disabled,
线下确认 没人提过，先改好了

2020-09-24 13:55 UTC, youluna approved these changes

2020-09-24 13:55 UTC, youluna commented on src/table/base.jsx
> +                rowSelection,
done

2020-09-24 13:56 UTC, youluna commented on src/menu/view/menu.jsx
> +            [`${prefix}menu-selectable-${selectMode}`]: selectMode,
主要是padding的变化，单选模式下padding小，多选模式下padding大

2020-09-24 14:03 UTC, merged