Doc/affix
alibaba-fusion/next pull request #2371
Opened 2020-11-16 06:48 UTC by mark-ck

Improve demo of Affix.

2020-11-18 09:26 UTC, galogm requested changes
都是没什么难度的点，随手改一下吧～

2020-11-18 09:26 UTC, galogm commented on docs/affix/index.md
>  ### 何时使用
何时使用是二级标题哟，前面## Guide废弃了，可以看一下文档指南里的目录结构：https://yuque.antfin.com/fusion-design-system/roa4lz/ea5nqx

2020-11-18 09:26 UTC, galogm commented on docs/affix/index.md
> +当内容区域比较长，需要滚动页面时，这部分内容对应的操作或者导航需要在滚动范围内始终展现。常用于侧边菜单和按钮组合。页面可视范围过小时，慎用此功能以免遮挡页面内容。
可以使用markdown无序列表，分割小点，结构更清晰哟～

2020-11-18 09:26 UTC, galogm commented on docs/affix/demo/custom-container.md
> +用 container 设置 Affix 需要监听其滚动事件的元素，默认为 window
不要忘了句号呐

2020-11-26 12:26 UTC, youluna approved these changes

2020-11-26 12:30 UTC, youluna commented on docs/affix/demo/basic.md
> +最简单的用法。
我感觉如果不在这里需要在其他地方，比如affix/index.md中解释affix是做什么的，左边这个删的不太好

2020-11-26 12:30 UTC, youluna commented on docs/affix/demo/custom-container.md
> +用 container 设置 Affix 需要监听其滚动事件的元素，默认为 window
我觉得原来写的更全面，更准确，container是个函数

2020-11-26 12:31 UTC, youluna commented on docs/affix/demo/custom-offset.md
> +可以通过 offsetTop 或 offsetBottom 自定义偏移量。
为什么把``去掉呢

2020-11-27 03:18 UTC, youluna approved these changes

2020-11-27 03:18 UTC, merged