Feat/button2.0
alibaba-fusion/next pull request #2563
Opened 2020-12-23 07:39 UTC by galogm

2021-01-27 08:33 UTC, youluna commented on src/button/index.jsx
> +            deprecated('warning', "type: PropTypes.oneOf(['normal', 'primary', 'warning', 'inverse])", 'Button');
这样报警信息会很多，而且没有重点，要求应当是“用户查看报警信息，根据报警信息可以简单快速修改当前组件props”。

判断信息需要写细致一些，例如
```
if (warning !== true && text === true && (type === 'primary')) {
    log.warn('<Button type="primary" text /> is deprecated, use  <Button type="primary" model="text" /> instead');
} else if () {}
else {
log.warn('warning, text is deprecated, use ')
}
```

参考 https://yuque.antfin.com/fusion-design-system/roa4lz/wb867r

2021-01-27 08:48 UTC, youluna commented
一个大原则是，原来用户的用法依然正常，不会有任何问题。这个原则似乎没有被满足
![image](https://user-images.githubusercontent.com/10049465/105966265-64bc1580-60bf-11eb-9c08-5136166e6452.png)
![image](https://user-images.githubusercontent.com/10049465/105966328-74d3f500-60bf-11eb-91a5-07d5f997010a.png)

2021-01-27 08:53 UTC, youluna requested changes
![image](https://user-images.githubusercontent.com/10049465/105966926-37239c00-60c0-11eb-89cd-9157c098b235.png)

2021-04-08 07:58 UTC, youluna commented on src/button/view/wave.jsx
> +        else if (/next-large/.test(node.className)) spread = '7px';
prefix是可以被改掉的，这种next-不准确，要换成${prefix}

2021-08-03 14:11 UTC, galogm commented
废弃

2021-08-03 14:11 UTC, closed without merging