fix(DatePicker): default format of WeekPicker, close #1491
alibaba-fusion/next pull request #2904
Opened 2021-04-20 08:41 UTC by jerryyxu

2021-04-22 02:23 UTC, youluna approved these changes

2021-04-22 02:24 UTC, youluna commented
![image](https://user-images.githubusercontent.com/10049465/115646509-dae5b680-a354-11eb-958e-434b43be3e17.png)
有单元测试没过

2021-04-23 07:07 UTC, youluna requested changes
单元测试哦

2021-04-29 12:51 UTC, jerryyxu commented
use this : https://github.com/alibaba-fusion/next/pull/2956

2021-04-29 12:51 UTC, closed without merging