fix(Cascader): suport immutable dataSource, close #1558
alibaba-fusion/next pull request #2905
Opened 2021-04-20 09:48 UTC by jerryyxu

2021-04-23 07:15 UTC, youluna commented
加一些comment吧，写一下为什么这么改，有点看不动orz

2021-04-25 09:45 UTC, youluna approved these changes

2021-04-25 09:53 UTC, youluna requested changes

2021-04-25 09:53 UTC, youluna commented on src/cascader/cascader.jsx
> +        if ((err.message || '').match('Cannot assign to read only property')) {
这种方式虽然对用户来说会很好用，但是太干了。用api的方式吧，tree的也需要改掉，用抛warning的方式，提示用户immutable的数据类型，需要开启新API，比如`immutableDataSource?: boolean`

2021-05-13 06:40 UTC, jerryyxu commented
use https://github.com/alibaba-fusion/next/pull/2984

2021-05-13 06:40 UTC, closed without merging