fix(Overlay): should set overflow hidden to container
alibaba-fusion/next pull request #3055
Opened 2021-06-01 14:06 UTC by jerryyxu

2021-06-01 14:08 UTC, youluna commented on src/overlay/overlay.jsx
> +        parent.scrollHeight > parent.clientHeight &&
parent or parentNode？

2021-06-01 14:12 UTC, youluna approved these changes

2021-06-02 02:35 UTC, youluna requested changes
关注下单元测试

2021-06-02 04:20 UTC, jerryyxu commented on src/overlay/overlay.jsx
> -    const doc = document.documentElement;
document.body.parentNode === document.documentElement

2021-06-02 04:22 UTC, jerryyxu commented on src/overlay/overlay.jsx
`getDerivedStateFromProps` 阶段拿不到父节点，涉及到 dom 节点的操作，需要在 `componentDidMount` 和 `componentDidUpdate` 中执行

2021-06-02 07:04 UTC, jerryyxu commented on src/overlay/overlay.jsx
> +    const parentNode = container.parentNode;
container   是通过 getContainerNode 中的 findNode 获取的

2021-06-02 10:15 UTC, youluna commented on src/overlay/overlay.jsx
> +        if (this.state.willOpen) {
差异：
- 旧版是在渲染前，getDerivedStateFromProps阶段，执行的beforeOpen beforeClose方法
- 新版是在渲染后，componentDidMount componentDidUpdate阶段执行上述方法。

理论上来说旧版更符合语义，但是旧版执行时dom节点都没有ready，这时给container加任何样式都会失败，(之前container都是body，body在最外层，执行时可以保证body一定是ready的。)

如下图，如果不调整beforeOpen执行时机，下面的测试用例就会报错，因为找不到挂载节点，无法给它设置样式
```jsx
<ConfigProvider popupContainer={'dialog-popupcontainer'}>
                <div id="dialog-popupcontainer" style={{ height: 300, overflow: 'auto' }}>
                    <Dialog title="Welcome to Alibaba.com" visible>
                        Start your business here by searching a popular product
                    </Dialog>
                </div>
            </ConfigProvider>
```

2021-06-02 11:28 UTC, youluna approved these changes

2021-06-02 11:28 UTC, merged