Fix input used with Chinese, should trigger onChange after IME finished
alibaba-fusion/next pull request #3091
Opened 2021-06-09 11:53 UTC by bindoon

2021-06-09 12:53 UTC, youluna commented on src/input/base.jsx
> +        let value = e.target.value;
`const ` instead of `let`

2021-06-09 12:59 UTC, youluna requested changes
需要测试用例哦

2021-06-10 05:18 UTC, bindoon commented
@youluna ReactWrapper::simulate() event 'onCompositionEnd' does not exist

simulate 不支持 onCompositionEnd 系列事件

2021-06-10 06:39 UTC, youluna commented
![image](https://user-images.githubusercontent.com/10049465/121476748-9e9c1180-c9f9-11eb-972b-80c469e3441c.png)
建议加一句话
- 1.23版本新增了API `composition `, 开启后可以在输入法结束后再触发onChange

2021-06-10 06:48 UTC, bindoon commented
改到 1.23 里面去支持。

2021-06-10 06:48 UTC, closed without merging