feat(Rating): add allowClear api
alibaba-fusion/next pull request #3174
Opened 2021-07-12 08:38 UTC by zuoqi705

2021-07-13 11:05 UTC, youluna commented
要加一下demo和测试用例哦

2021-07-13 11:08 UTC, youluna requested changes

2021-07-13 11:08 UTC, youluna commented on src/rating/rating.jsx
> -        if (value !== this.state.hoverValue) {
这个判断逻辑要保留，不保留的话不管有没有设置allowClear，都是清除模式了

2021-07-14 10:13 UTC, zuoqi705 commented on src/rating/rating.jsx
> -        if (value !== this.state.hoverValue) {
不会啊

2021-07-14 12:04 UTC, youluna approved these changes

2021-07-14 12:05 UTC, merged