fix(Calendar): showOtherMonth=false style, close #3321
alibaba-fusion/next pull request #3348
Opened 2021-09-17 07:24 UTC by weinianyang

2021-09-17 08:31 UTC, bindoon commented
有一个单测没过
![image](https://user-images.githubusercontent.com/5189853/133751264-3e536d6d-8a1a-44d8-9fdc-497c878daf1f.png)

本地跑 tnpm run test calendar 排查下

2021-09-17 08:40 UTC, weinianyang commented
![image](https://user-images.githubusercontent.com/90443688/133752356-7a692082-8db7-43c1-8a33-64235f507372.png)

2021-09-17 10:24 UTC, bindoon commented on src/calendar/table/date-table.jsx
> +                        month={currentDate.format('M')}
td 上面没有 month 属性

2021-09-17 10:58 UTC, bindoon commented on src/calendar/table/date-table.jsx
> +            } else if (firstDayOfMonth.format('M') * 1 >= pageFirstMonth) {
描述写这里的逻辑

2021-09-17 11:35 UTC, bindoon commented on src/calendar/calendar.jsx
> +                this.props.onSelect(date);
showOtherMonth=false 后是不是 onSelect 也触发不了了。

2021-09-18 06:26 UTC, youluna requested changes

2021-09-18 06:26 UTC, youluna commented on src/calendar/table/date-table.jsx
> +                */
````jsx
if (!showOtherMonth && (lastDayOfWeekInCurrentMonth || firstDayOfWeekInCurrentMonth)) {
                monthElements.push(
                    <tr key={i} role="row">
                        {weekElements}
                    </tr>
                );
            }
````

2021-09-18 09:34 UTC, youluna requested changes

2021-09-18 09:34 UTC, youluna commented on src/calendar/calendar.jsx
> +        if (showOtherMonth) {
可以走跳出

2021-09-18 10:21 UTC, merged