Feat(TreeSelect): use tagInline to support single line display, close #3360
alibaba-fusion/next pull request #3445
Opened 2021-10-25 09:43 UTC by lakerswgq

2021-11-04 09:23 UTC, lakerswgq commented
> 可以再加个demo，表明一下用法 ![image](https://user-images.githubusercontent.com/10049465/138829546-7b64f5d2-3bd4-4574-b8b8-85dd8609c10b.png)

已经加了

https://github.com/alibaba-fusion/next/blob/430020be05037375e07ad120a592e9e9293832a6/docs/tree-select/demo/inline.md?plain=1#L1

2021-11-04 09:24 UTC, lakerswgq commented on docs/tree-select/demo/inline.md
> +# 单行显示
@youluna demo 在这里

2021-11-16 08:32 UTC, youluna requested changes
`npm run api tree-select` 然后 补充下英文

2021-11-16 08:32 UTC, youluna commented on src/tree-select/tree-select.jsx
> +         * @param {Object[]} totalValues 总待选元素
```jsx
* @version 1.25
```

2021-11-16 08:32 UTC, youluna commented on src/tree-select/tree-select.jsx
> +         * 是否一行显示，仅在 multiple 和 treeCheckable 为 true 时生效
```jsx
* @version 1.25
```

2021-11-17 06:42 UTC, youluna approved these changes

2021-11-17 09:32 UTC, merged