fix(Menu): resolve 3825 issue
alibaba-fusion/next pull request #3827
Opened 2022-03-25 09:15 UTC by Summer-andy

修复Menu 的 Divider 在被 <> 包裹的场景页面崩溃的问题

2022-03-25 09:43 UTC, youluna commented on src/menu/view/menu.jsx
> +import { has } from 'lodash';
目前lodash没有全量引入，建议手写一下这个判断，不要引入新的依赖，新的依赖需要升级Y位

2022-03-25 09:43 UTC, youluna commented on src/menu/view/menu.jsx
> +            }
加了这个判断之后会有问题吧？之前string类型的child，是直接渲染的，加了之后就什么都不渲染了

2022-03-25 09:43 UTC, youluna commented on src/menu/view/menu.jsx
> +                return loop(child.props.children, '0');
这里是为了解决什么问题？可以文字解释下？

2022-03-29 06:34 UTC, youluna requested changes

2022-03-29 06:34 UTC, youluna commented on src/menu/view/menu.jsx
> +                return loop(child.props.children, '0');
176行的第二个参数是不是应当是posPrefix ？

2022-03-29 06:34 UTC, youluna commented on src/menu/view/menu.jsx
> +                has(child, 'props.children') &&
换成  `child && child.props && child.props.children &&` 是不是也可以

2022-09-07 06:04 UTC, lakerswgq commented
这个 pr 还有需求吗，#3825 这个 issue 我看已经关闭了，这里后续没有动作我也关闭了

2022-09-14 09:08 UTC, closed without merging