fix(Dialog): use "确定" instead of "确认" for zh-cn
alibaba-fusion/next pull request #3835
Opened 2022-03-30 08:16 UTC by lakerswgq

2022-03-30 08:18 UTC, lakerswgq commented
![image](https://user-images.githubusercontent.com/9381522/160784964-e8afe6f5-b62f-428d-adc4-11b1a2fbccad.png)

统一为确定

2022-03-31 02:30 UTC, bindoon approved these changes

2022-03-31 02:30 UTC, bindoon commented
单测里面要修改下，有”确定“ 的判断

2022-03-31 02:31 UTC, bindoon requested changes
单测里面要修改下，有”确定“ 的判断

2022-03-31 02:38 UTC, lakerswgq commented
> 单测里面要修改下，有”确定“ 的判断

ok，呆会我看下具体 case

2022-03-31 06:13 UTC, bindoon approved these changes

2022-03-31 06:14 UTC, merged