fix(CascaderSelect): a typesetting error occurred while being at the …
alibaba-fusion/next pull request #4455
Opened 2023-10-09 03:09 UTC by YunMeng99

…edge of the page close #4309

2023-10-12 02:51 UTC, eternalsky commented
改成 flex 布局之后，其他地方的样式没有出现问题吗，flex 还是有很多隐藏的性质的。

2023-10-17 10:52 UTC, YSMJ1994 approved these changes

2023-10-19 06:44 UTC, YunMeng99 commented
> > 改成 flex 布局之后，其他地方的样式没有出现问题吗，flex 还是有很多隐藏的性质的。
> 
> @YunMeng99 仔细看了一下代码，应该是cascader组件的componentDidUpdate里计算容器宽度因为一些原因没有生效的原因，跟样式没有关系

pr 已更新

2023-10-19 07:20 UTC, YSMJ1994 commented
@YunMeng99 comment 了

2023-10-19 09:46 UTC, YSMJ1994 requested changes

2023-10-20 07:04 UTC, YunMeng99 commented on src/cascader/cascader.jsx
> +                <div className={`${prefix}cascader-inner`}>
更新了pr

2023-10-24 11:16 UTC, YSMJ1994 approved these changes

2023-10-24 11:18 UTC, merged