feat(Breadcrumb):Add a callback triggered by clicking the menu in the…
alibaba-fusion/next pull request #4457
Opened 2023-10-09 10:52 UTC by YunMeng99

… popup layer  close #4359

2023-10-12 11:25 UTC, eternalsky commented
我看现在普通的 item 也是没有 onClick 的事件的，感觉Menu 里的也没有必要加吧，应该按照同样的方式处理

2023-10-18 11:44 UTC, YSMJ1994 commented
@YunMeng99 需要补充一下测试用例

2023-10-31 08:26 UTC, YSMJ1994 requested changes
onClick事件不建议封装用户可以获取到的参数，直接传递原始的MouseEvent即可

2023-10-31 08:26 UTC, YSMJ1994 commented on test/breadcrumb/index-spec.js
> +        assert(isObjectEqual(isClicked, { children: 'Whatever 2', link: 'javascript:void(0);', key: undefined }));
可以用assert.deepEqual

2023-10-31 08:26 UTC, YSMJ1994 commented on types/breadcrumb/index.d.ts
> +    onClick?: () => void;
函数参数的类型需要补充一下

2023-10-31 08:26 UTC, YSMJ1994 commented on src/breadcrumb/item.jsx
> +                onClick={() => onClick && onClick({ children, link, key })}
这里建议将MouseEvent 传递给onClick，然后 { children, link, key  }这些参数用户其实可以自己获取到的，我们这里没有必要再传回给用户

2023-10-31 08:26 UTC, YSMJ1994 commented on docs/breadcrumb/index.en-us.md
> +| onClick   | Click event | Function() => void
这里需要完善一下函数参数

2023-10-31 08:26 UTC, YSMJ1994 commented on docs/breadcrumb/index.md
> +| onClick | 单击事件 | Function() => void
同上

2023-10-31 09:55 UTC, YSMJ1994 approved these changes

2023-10-31 09:57 UTC, merged