fix(DatePicker2): change inputValue when only mode changes
alibaba-fusion/next pull request #4486
Opened 2023-10-23 07:10 UTC by kyokaxin

close #4090

2023-10-23 07:46 UTC, eternalsky commented
@kyokaxin 我看原版的 issue ，还有 need reproduce 和 insufficient information 的标。目前问题已经明确了吗

2023-10-23 07:50 UTC, kyokaxin commented
> @kyokaxin 我看原版的 issue ，还有 need reproduce 和 insufficient information 的标。目前问题已经明确了吗

问题明确了，我把这两个标去掉

2023-10-23 07:53 UTC, eternalsky commented
> > @kyokaxin 我看原版的 issue ，还有 need reproduce 和 insufficient information 的标。目前问题已经明确了吗
> 
> 问题明确了，我把这两个标去掉

@kyokaxin 这个问题能大致说下是怎么个意思吗，光看 issue 没太看懂。

2023-10-23 08:12 UTC, kyokaxin commented
> > > @kyokaxin 我看原版的 issue ，还有 need reproduce 和 insufficient information 的标。目前问题已经明确了吗
> > 
> > 
> > 问题明确了，我把这两个标去掉
> 
> @kyokaxin 这个问题能大致说下是怎么个意思吗，光看 issue 没太看懂。

在value保持不变均为7天的情况下([2023-10-16', '2023-10-22])，切换mode值(从date变为week)，上面显示的inputValue没有发生变化

2023-10-23 08:45 UTC, YSMJ1994 requested changes
测试用例要确保准确、可用

2023-10-23 08:45 UTC, YSMJ1994 commented on test/date-picker2/index-spec.js
> +            mode = WEEK;
这里测试用例应该 
1. 原来的值是否正确显示
2. 只切换props里的mode
3. 检查值是否正确显示

你这里切换props的方法不对，断言少了一个

2023-10-23 08:45 UTC, YSMJ1994 commented on test/date-picker2/index-spec.js
> +                done();
这里的done是多余的

2023-10-24 01:49 UTC, eternalsky commented on test/date-picker2/index-spec.js
> +            wrapper.setProps({ mode: WEEK });
@kyokaxin 这里为何不复用修改了的 mode 变量呢？

2023-10-24 01:51 UTC, kyokaxin commented on test/date-picker2/index-spec.js
> +            wrapper.setProps({ mode: WEEK });
没注意，我重新改一下

2023-10-24 02:01 UTC, eternalsky approved these changes
LGTM @YSMJ1994 再看看

2023-10-24 02:13 UTC, YSMJ1994 approved these changes

2023-10-24 02:13 UTC, YSMJ1994 approved these changes

2023-10-24 02:14 UTC, merged