feat(upload): add param to control upload list
alibaba-fusion/next pull request #4500
Opened 2023-10-30 01:40 UTC by owenchen1004

现有的upload组件无法隐藏上传列表，在listType属性上加了“none”参数来控制上传列表的显隐，默认显示上传列表。

Fixes  #4496

2023-10-30 02:07 UTC, YSMJ1994 requested changes

2023-10-30 02:07 UTC, YSMJ1994 commented on src/upload/upload.jsx
> +                {(listType && listType !== 'none') || list ? (
这里的逻辑应该是 listType && listType !== 'none' && list

2023-10-30 02:08 UTC, YSMJ1994 commented
还有，测试用例需要补充一下，关于listType为none的情况和不为none的情况是否符合预期

2023-10-30 03:48 UTC, owenchen1004 commented on src/upload/upload.jsx
> +                {(listType && listType !== 'none') || list ? (
这样写测试是挂的，list好像获取的都是undefined，上传文件后list也依然是undefined。这里像是有个bug。

2023-10-30 07:37 UTC, YSMJ1994 commented on src/upload/upload.jsx
> +                {(listType && listType !== 'none') || list ? (
好的，这个list貌似是一个没用的属性，忽略吧，后面我们再看下这个list

2023-10-30 09:39 UTC, owenchen1004 commented
> 还有，测试用例需要补充一下，关于listType为none的情况和不为none的情况是否符合预期

测试用例已补充

2023-10-31 08:52 UTC, YSMJ1994 approved these changes

2023-10-31 08:55 UTC, merged