fix(Cascader): cascader props value changed then expandedValue did no…
alibaba-fusion/next pull request #4531
Opened 2023-11-16 12:38 UTC by seven-lh

…t change

2023-11-20 08:16 UTC, seven-lh commented
cascader props value expanded Value

2023-11-30 06:06 UTC, eternalsky requested changes

2023-11-30 06:06 UTC, eternalsky commented on src/cascader/cascader.jsx
> +        const { expandedValue, _v2n, _p2n } = this.state;
已 API 的形式进行父子组件通信并不是推荐的 React 编写范式，expandedValue 的修改应该在 getDeriveStateFromProps 中想办法完成。 @seven-lh

2023-11-30 06:14 UTC, eternalsky commented
@YSMJ1994 这个 pr 解决的 issue，貌似与另一个 pr 有些关联：https://github.com/alibaba-fusion/next/commit/c8ed0b5096914d0a59c5eb1a4227226e1409a50c。可以一起来看一下。另一个 pr 中，加入了 state.isExpandedValueSetByAction 限制了根据值重置 expandedValue 的逻辑，而这个 pr 关联的 issue 貌似就是这个的反例，即value 变化从外部而外，但 isExpandedValueSetByAction 并未改变，导致 expandedValue 没有重置。

2023-11-30 07:04 UTC, eternalsky commented on src/cascader/cascader.jsx
> +        const { expandedValue, _v2n, _p2n } = this.state;
@seven-lh 我觉得合适的改法，应该是继续完善 getDeriveStateFromProps 中对 expandedValue 重置逻辑的修改，应该考虑到 props.value 变化时重置 expandedValue 的逻辑。

2023-11-30 07:07 UTC, YSMJ1994 commented on src/cascader/cascader.jsx
> +        const { expandedValue, _v2n, _p2n } = this.state;
@eternalsky 这块内容后续是我来跟进的。感觉是当value变更时，需要执行一下这个 updateExpandedValue里面的逻辑，若当前的expandedValue在value中匹配则不操作，若不匹配则重置

2023-12-01 08:21 UTC, eternalsky commented on src/cascader/cascader.jsx
> +        const { expandedValue, _v2n, _p2n } = this.state;
@YSMJ1994 意思这个 pr 的后续修改是你来跟进吗~ 改进思路，我下面也有提到，其实这个是一个典型的半受控逻辑。即外面不动时受里面控制，外面动时受外面控制。应该在 getDeriveStateFromProps 中加入对 props.value 前后值比较的逻辑。

2023-12-04 07:40 UTC, eternalsky approved these changes

2023-12-06 02:53 UTC, merged