feat(balloon): control arrow of tooltip
alibaba-fusion/next pull request #4532
Opened 2023-11-17 01:19 UTC by owenchen1004

Tooltip应该是一个最简单的Balloon，并在广泛引用的场景中，Tooltip被希望以一个不带箭头的的浮层提示形式出现。

新增了可以隐藏Tooltip箭头的选项，使之可以成为一个不带箭头的文字提示气泡框。

效果如下：
<img width="192" alt="image" src="https://github.com/alibaba-fusion/next/assets/56390399/275bffe8-98a1-433c-a469-bcc175be1bd8">

2023-11-22 09:48 UTC, YSMJ1994 commented on docs/balloon/index.md
> +| arrow | 是否展示tooltip中的箭头                                                                                                                                                          | Boolean      | tru
这个文档不需要手动添加，编译时会根据 PropTypes内定义的jsdoc自动生成

2023-11-22 09:48 UTC, YSMJ1994 commented on src/balloon/inner.jsx
> +        arrow: PropTypes.bool,
这个新props需要在 src/balloon/tooltip组件的 PropTypes内添加，并填上对应的jsdoc

2023-11-22 09:48 UTC, YSMJ1994 commented on test/balloon/tooltip-spec.js
> +        arrowFalseWrapper = mount(
这里的渲染逻辑没有复用场景的话，需要放到对应的 spec 内部，用例结束时也需要执行unmount

2023-11-23 03:27 UTC, owenchen1004 commented
以上bug已修复并提交

2023-11-23 03:27 UTC, owenchen1004 commented on docs/balloon/index.md
> +| arrow | 是否展示tooltip中的箭头                                                                                                                                                          | Boolean      | tru
已修复

2023-11-29 13:42 UTC, YSMJ1994 commented on test/balloon/tooltip-spec.js
> +    let arrowFalseWrapper = {};
这个变量其实并没有被复用，无需提升到这里定义

2023-11-29 13:42 UTC, YSMJ1994 commented on test/balloon/tooltip-spec.js
> +            <Tooltip trigger={trigger} triggetType="hover" arrow={true}>
arrow默认为true，这里无需手动添加

2023-11-29 13:42 UTC, YSMJ1994 commented on test/balloon/tooltip-spec.js
> +        arrowFalseWrapper.unmount();
unmount时机不对，应该在setTimeout内部

2023-12-05 01:20 UTC, owenchen1004 commented
感谢指点，已更改并通过测试

2023-12-05 02:20 UTC, YSMJ1994 requested changes

2023-12-05 02:20 UTC, YSMJ1994 commented on test/balloon/tooltip-spec.js
> +            arrowFalseWrapper.unmount();
应该在done之前unmount

2023-12-05 02:20 UTC, YSMJ1994 commented on src/balloon/tooltip.jsx
>      static defaultProps = {
这里也需要定义 arrow的默认值，文档生成是从这里解析的，不定义的话默认值不会体现在文档内

2023-12-05 02:20 UTC, YSMJ1994 commented on src/balloon/tooltip.jsx
> +                arrow={arrow}
这里的单独解构传递是多余的

2023-12-05 02:20 UTC, YSMJ1994 commented on test/balloon/tooltip-spec.js
> +        let arrowFalseWrapper = mount(
const

2023-12-05 02:26 UTC, owenchen1004 commented
已更新

2023-12-05 02:30 UTC, YSMJ1994 commented
> 已更新

没看到新的commit变化

2023-12-05 02:49 UTC, owenchen1004 commented
> > 已更新
> 
> 没看到新的commit变化

现在传上去了

2023-12-05 03:06 UTC, YSMJ1994 commented
现在Balloon的 arrow实现也是使用这个 next-balloon-arrow元素了，这个 arrow 属性也可以支持到balloon组件上，可以的话也一起加一下吧，单独给 tooltip 支持用户可能会有困惑
这个 issue   https://github.com/alibaba-fusion/next/issues/4186

2023-12-05 03:19 UTC, owenchen1004 commented
> #4186

好的 我加一下

2023-12-06 02:35 UTC, owenchen1004 commented
拉完maser的代码，测试没跑通过呀，会报autoAdjust when in the fixed box and followTrigger=true

2023-12-07 03:18 UTC, owenchen1004 commented
> 现在Balloon的 arrow实现也是使用这个 next-balloon-arrow元素了，这个 arrow 属性也可以支持到balloon组件上，可以的话也一起加一下吧，单独给 tooltip 支持用户可能会有困惑 这个 issue #4186

已添加

2023-12-27 07:44 UTC, closed without merging

2023-12-27 07:47 UTC, YSMJ1994 commented
抱歉，项目正在重构，还未合并PR因此关闭了，有需要可以重新基于master提交PR~