Fix/table scroll to row
alibaba-fusion/next pull request #4648
Opened 2023-12-12 10:30 UTC by YunMeng99

2023-12-12 13:26 UTC, YSMJ1994 requested changes
1. PR里混杂了overlay的代码，是否是基于master检出的分支？
2. 从实际含义上来说，新增的api命名为 keepForwardRenderRows 更合理
3. demo内的解释不够清晰，参考: 虚拟滚动会卸载滚动到视区之外的行，行合并利用td元素的rowSpan属性，需要在合并的第一行设置rowSpan属性，若因滚动视区外卸载了该行，则会导致行合并失效，可以使用 keepForwardRenderRows 设置向前保留一定行数不被卸载，从而使行合并始终生效（设置 keepForwardRenderRows 大于 max rowSpan即可）
4. demo缺少交互演示设置不同 keepForwardRenderRows 的效果
5. 需要在table/base.jsx的propTypes内添加该api的jsdoc，文档api会依据这个jsdoc自动生成的

2023-12-13 12:03 UTC, YSMJ1994 requested changes

2023-12-13 12:03 UTC, YSMJ1994 commented on types/table/index.d.ts
> +    keepForwardRenderRows?: Number;
tsdoc需要补充，类型要使用基本类型 number

2023-12-13 12:03 UTC, YSMJ1994 commented on src/table/virtual.jsx
> +                THRESHOLD: this.props.keepForwardRenderRows,
这里为何要使用一个本地状态储存

2023-12-13 12:04 UTC, YSMJ1994 commented
测试用例我后面帮你优化一下，你先改前面的内容 @YunMeng99

2023-12-14 04:04 UTC, eternalsky approved these changes

2023-12-14 06:23 UTC, YSMJ1994 approved these changes

2023-12-14 06:35 UTC, merged