chore(Dropdown): ts & docs &test
alibaba-fusion/next pull request #4699
Opened 2024-01-04 03:49 UTC by woshilaoge

2024-01-08 08:50 UTC, YSMJ1994 commented on components/dropdown/__tests__/index-spec.tsx
> +        cy.document().then(document => {
此处参考：

```tsx

cy.mount(
    <Dropdown
        autoFocus
        trigger={<button className="trigger">Hello dropdown</button>}
        animation={false}
    >
        <Menu>
            <Menu.Item>Option 1</Menu.Item>
            <Menu.Item>Option 2</Menu.Item>
            <Menu.Item>Option 3</Menu.Item>
            <Menu.Item>Option 4</Menu.Item>
        </Menu>
    </Dropdown>
);
cy.clock();
cy.get('.trigger').trigger('mouseover');
cy.tick(500).then(() => {
    cy.wrap(document.activeElement).should('not.have.class', 'next-menu-item');
});
```

2024-01-25 09:25 UTC, woshilaoge commented on components/dropdown/types.ts
> +    animation?: object | boolean;
done

2024-01-25 09:26 UTC, woshilaoge commented on components/dropdown/types.ts
> +    trigger?: React.ReactElement<any, string | React.JSXElementConstructor<any>> | undefined;
done

2024-01-25 09:27 UTC, woshilaoge commented on components/dropdown/types.ts
> +    triggerType?: string | Array<string>;
done

2024-01-25 09:35 UTC, woshilaoge commented on components/dropdown/dropdown.tsx
> +    static getDerivedStateFromProps(nextProps: { visible: unknown }) {
done

2024-01-25 09:36 UTC, woshilaoge commented on components/dropdown/dropdown.tsx
> +    constructor(props: DropdownProps | Readonly<DropdownProps>) {
done

2024-01-25 09:38 UTC, woshilaoge commented on components/dropdown/dropdown.tsx
> +/* eslint-disable tsdoc/syntax */
done

2024-01-25 09:41 UTC, woshilaoge commented on components/dropdown/__tests__/index-spec.tsx
> +        cy.document().then(document => {
done

2024-03-14 08:52 UTC, YSMJ1994 commented on components/dropdown/types.ts
> +    animation?: object | boolean;
继承自 Overlay 的属性最好是直接引用 overlayProps ，这样避免两边需要同步改造，而且现在 overlay 还未改造完成..

2024-03-14 09:22 UTC, YSMJ1994 requested changes

2024-03-14 09:22 UTC, YSMJ1994 commented on components/dropdown/__tests__/index-spec.tsx
>      it('autoFocus=false should not have any activeElement', done => {
此处 done 需移除，否则用例会超时异常

2024-03-14 09:22 UTC, YSMJ1994 commented on components/dropdown/__tests__/index-spec.tsx
> +                autoFocus
autoFocus={false}

2024-03-14 09:22 UTC, YSMJ1994 commented on components/dropdown/__tests__/index-spec.tsx
> +        ReactTestUtils.Simulate.keyDown(document.activeElement as Element, {
应使用 cy.get('.trigger').click() 替代

2024-03-14 09:22 UTC, YSMJ1994 commented on components/dropdown/__tests__/index-spec.tsx
> +            cy.wrap(document.activeElement).should('not.have.class', 'next-menu-item');
此处应先断言 .next-menu 元素存在，代表弹窗已经出现，再判断active元素不是 menu item

2024-03-14 09:22 UTC, YSMJ1994 commented on components/dropdown/types.ts
> +    children?: React.ReactElement;
从代码来看，children 属性应必填

2024-03-14 09:22 UTC, YSMJ1994 commented on components/dropdown/types.ts
> +export interface DropdownProps extends React.HTMLAttributes<HTMLElement>, CommonProps, PopupProps {
下面所有引用自 PopupProps 的属性都要以 `PopupProps['xxx']` 的形式定义类型，避免 overlay 组件升级完成后还要同步改造这些地方

2024-03-14 09:22 UTC, YSMJ1994 commented on components/dropdown/__tests__/a11y-spec.tsx
> +            // eslint-disable-next-line jsx-a11y/anchor-is-valid
多余的 eslint-disable

2024-03-15 02:41 UTC, woshilaoge commented on components/dropdown/types.ts
> +    animation?: object | boolean;
animation?: PopupProps['animation'];
    已调整类似引用

2024-03-15 02:48 UTC, woshilaoge commented on components/dropdown/dropdown.tsx
> +        const child = Children.only(this.props.children) as React.ReactPortal;
children: React.ReactElement;已调整为必填

2024-03-15 02:50 UTC, woshilaoge commented on components/dropdown/dropdown.tsx
> +        const child = Children.only(this.props.children) as React.ReactPortal;
children: React.ReactElement;已调整为必填

2024-03-15 03:06 UTC, woshilaoge commented on components/dropdown/__tests__/a11y-spec.tsx
> +            // eslint-disable-next-line jsx-a11y/anchor-is-valid
done

2024-03-26 03:22 UTC, YSMJ1994 commented
因为这个组件 api 大量继承了 Overlay.Popup 组件的 api ，从可读性来看全部使用 `Popup['xxx']` 的方式展示文档不太友好，起不到指导作用，且 overlay 组件目前还未完成改造，很多类型不太正确，直接复制过来也不合适，先 hold 吧，等 overlay 改造完成后再调整 api 类型定义

2024-05-30 02:32 UTC, eternalsky commented
由于人员变动，先把 pr merge，后续再进一步处理。

2024-05-30 02:33 UTC, merged