Feat/field
alibaba-fusion/next pull request #4710
Opened 2024-01-10 07:43 UTC by qingniaotonghua

2024-02-22 02:44 UTC, eternalsky requested changes

2024-02-22 02:44 UTC, eternalsky commented on components/field/index.ts
> +    validate = this.validateCallback;
这样的写法感觉有些问题，validate 从成员函数变成了成员变量，性质发生了变化。

2024-02-22 02:44 UTC, eternalsky commented on components/field/types.ts
> +import { type FieldOption as OriginalFieldOption } from '@alifd/field';
这里没有 tsdoc，文档如何生成？

2024-02-22 02:44 UTC, eternalsky commented on components/field/index.ts
> +     * @param backToDefault - 是否重置为默认值，默认 false
这种用法从下面的逻辑看是 deprecated 的。tsdoc 应该也给予提示。

2024-02-22 02:49 UTC, eternalsky commented on components/field/index.ts
> +            super.reset(ns as string | string[]);
如果 super.reset 确实不接受 false，那这里改成 super.reset(ns === false ? undefined : ns); 是不是更合理一些。

2024-03-01 03:44 UTC, YSMJ1994 commented on components/field/index.ts
> +    validate = this.validateCallback;
主要是 validateCallback 有重载，不这样就需要在这里复制一遍重载，然后用起来其实没什么区别

2024-03-01 06:17 UTC, YSMJ1994 commented on components/field/types.ts
> +import { type FieldOption as OriginalFieldOption } from '@alifd/field';
field 的文档目前是手动维护的，暂时不用自动生成

2024-03-06 10:13 UTC, eternalsky approved these changes

2024-03-07 03:11 UTC, merged