Feat/collapse
alibaba-fusion/next pull request #4713
Opened 2024-01-10 10:17 UTC by qingniaotonghua

2024-01-31 09:28 UTC, eternalsky requested changes

2024-01-31 09:28 UTC, eternalsky commented on components/collapse/collapse.tsx
> +import React, { MouseEventHandler, ReactElement } from 'react';
没有 import type

2024-01-31 09:28 UTC, eternalsky commented on components/collapse/collapse.tsx
> +            expandedKeys: typeof expandedKeys === 'undefined' ? [] : (expandedKeys as string[]),
这个 as string[] 没有必要

2024-01-31 09:28 UTC, eternalsky commented on components/collapse/collapse.tsx
> +        const id = this.genratePanelId(item.id as number, index) as string;
这个 as number 不需要，应该是 genratePanelId 的第一个参数允许传 undefined

2024-01-31 09:28 UTC, eternalsky commented on components/collapse/collapse.tsx
> +        const id = this.genratePanelId(item.id as number, index) as string;
as string 感觉也不需要，只需要在 id 必须不为空是做不为空指定即可。

2024-01-31 09:28 UTC, eternalsky commented on components/collapse/collapse.tsx
> +                ? undefined
这里为什么要把 null 改成 undefined？如果传 null 并不影响组件逻辑，感觉应该是 onClick 要支持传 null

2024-01-31 09:28 UTC, eternalsky commented on components/collapse/collapse.tsx
> +        const className = this.props!.className as string;
props 不可能不存在吧，这个 ！加的有点奇怪。这个 as string 也不需要加，还是在需要判空的地方，加不为空的指定。

2024-01-31 09:28 UTC, eternalsky commented on components/collapse/panel.tsx
> +import React, { KeyboardEvent } from 'react';
没有 import type

2024-01-31 09:28 UTC, eternalsky commented on components/collapse/panel.tsx
> +import { PanelProps } from './types';
没有 import type

2024-01-31 09:28 UTC, eternalsky commented on components/collapse/panel.tsx
> +            onClick && onClick(e as unknown as React.MouseEvent<HTMLDivElement>);
这个地方感觉有点问题，应该是上面指定 e 的地方，指定的不够准确

2024-01-31 09:28 UTC, eternalsky commented on components/collapse/panel.tsx
> +            onClick && onClick(e as unknown as React.MouseEvent<HTMLDivElement>);
从实现上来看，这里说明，onClick 的 e 应该有两种，这应该在 onClick 的 types 中表明。

2024-01-31 09:28 UTC, eternalsky commented on components/collapse/types.ts
> +    // onClick?: (e: React.MouseEvent<HTMLDivElement> | React.KeyboardEvent<HTMLDivElement>) => void
这个注释有点奇怪

2024-01-31 09:28 UTC, eternalsky commented on components/collapse/types.ts
>  export interface PanelProps extends HTMLAttributesWeak, CommonProps {
需要加 @api

2024-01-31 09:28 UTC, eternalsky commented on components/collapse/types.ts
> +export type DataItem = {
需要加 @api

2024-01-31 09:28 UTC, eternalsky commented on components/collapse/types.ts
>  export interface CollapseProps extends React.HTMLAttributes<HTMLElement>, CommonProps {
需要加 @api

2024-01-31 09:28 UTC, eternalsky commented on components/collapse/__tests__/index-spec.tsx
> +import React, { ReactElement } from 'react';
没有 import type

2024-01-31 09:28 UTC, eternalsky commented on components/collapse/__tests__/index-spec.tsx
> +                cy.get('.next-collapse-panel-expanded').should('have.length', 1);
这个 tc 和原版的意思不太一致，原版的意思是第三个 panel 是展开的，改之后变成了有一个是展开的。

2024-01-31 09:28 UTC, eternalsky commented on components/collapse/__tests__/index-spec.tsx
> +                cy.get('.next-collapse-panel-expanded').should('have.length', 1);
这里和上面的 tc 有同样的问题

2024-03-07 03:58 UTC, eternalsky commented on components/collapse/collapse.tsx
> +         * 默认展开 keys
propTypes 里的可以删掉了。

2024-03-07 03:58 UTC, eternalsky commented on components/collapse/types.ts
> + * @api
这里后面不跟着名字也可以吗？会直接读 type 名？

2024-03-07 04:36 UTC, YSMJ1994 commented on components/collapse/types.ts
> + * @api
会直接读 type 的

2024-03-07 05:59 UTC, eternalsky approved these changes

2024-03-07 06:33 UTC, merged