refactor(NumberPicker):  Document optimization & Upgrade testing tools and optimize use cases & rename to ts
alibaba-fusion/next pull request #4753
Opened 2024-02-20 12:45 UTC by luolin-ck

number-picker新增功能如下：
1. TS化
2.文档优化
3. 测试工具升级，用例优化

2024-02-22 07:10 UTC, luolin-ck commented
close #4596

2024-03-26 11:44 UTC, YSMJ1994 requested changes
另外合并一下 master 分支，然后执行 `npm run check number-picker` 来检查错误和Warning，在不改动代码逻辑的前提下，尽量修复 eslint warning

2024-03-26 11:44 UTC, YSMJ1994 commented on components/number-picker/number-picker.tsx
> +        const stepString = step ? step.toString() : '';
step 有默认值，直接 `this.props.step!.toString()` 即可

2024-03-26 11:44 UTC, YSMJ1994 commented on components/number-picker/number-picker.tsx
> +        return Math.max(precision, this.props.precision ?? 0);
precision 有默认值

2024-03-26 11:44 UTC, YSMJ1994 commented on components/number-picker/number-picker.tsx
> +        if (isNaN(value as unknown as number)) {
多余的 as unknown

2024-03-26 11:44 UTC, YSMJ1994 commented on components/number-picker/number-picker.tsx
> +            .plus(step as string | number)
step 有默认值，这里直接 step! 即可

2024-03-26 11:44 UTC, YSMJ1994 commented on components/number-picker/number-picker.tsx
> +            .minus(step as string | number)
step 有默认值，直接 step! 即可

2024-03-26 11:44 UTC, YSMJ1994 commented on components/number-picker/number-picker.tsx
> +    saveInputRef(ref: HTMLInputElement) {
ref 类型应为 `React.ComponentRef<typeof Input> | null`

2024-03-26 11:44 UTC, YSMJ1994 commented on components/number-picker/number-picker.tsx
> +            [className ?? '']: className,
className 作为参数传递即可，参考: `classNames({...}, className) `

2024-03-26 11:44 UTC, YSMJ1994 commented on components/number-picker/number-picker.tsx
> +                            aria-hidden="true"
技术改造不做业务改造，这里不要多加 `aria-hidden="true"`

2024-03-26 11:44 UTC, YSMJ1994 commented on components/number-picker/number-picker.tsx
> +                            aria-hidden="true"
同上

2024-03-26 11:44 UTC, YSMJ1994 commented on components/number-picker/number-picker.tsx
> +                    <Icon type="minus" aria-hidden="true" className={`${prefixCls}-minus-icon`} />
同上

2024-03-26 11:44 UTC, YSMJ1994 commented on components/number-picker/number-picker.tsx
> +                    <Icon type="add" aria-hidden="true" className={`${prefixCls}-add-icon`} />
同上

2024-03-26 11:44 UTC, YSMJ1994 commented on components/number-picker/number-picker.tsx
> +            [className ?? '']: !!className,
参考 `classNames({...}, className)`

2024-03-26 11:44 UTC, YSMJ1994 commented on components/number-picker/number-picker.tsx
> +                    min={min as number | undefined}
多余的 `| undefined`

2024-03-26 11:44 UTC, YSMJ1994 commented on components/number-picker/__docs__/demo/accessibility/index.tsx
> +interface AppState {
这里可以参考一下 `box/__docs__/demo/wrap` 里面的写法，避免单独声明 Props 和 State 的类型

2024-03-26 11:44 UTC, YSMJ1994 commented on components/number-picker/__docs__/demo/accessibility/index.tsx
> +    onChange(value: number, e: Event) {
e 没用到可以删除

2024-03-26 11:44 UTC, YSMJ1994 commented on components/number-picker/__docs__/demo/accessibility/index.tsx
> +            num = value.toString();
避免改实现逻辑，给 num 设置 `string | number` 类型就好了

2024-03-26 11:44 UTC, YSMJ1994 commented on components/number-picker/__docs__/demo/basic/index.tsx
> +function onChange(value: number, e: any) {
no any

2024-03-26 11:44 UTC, YSMJ1994 commented on components/number-picker/__docs__/demo/editable/index.tsx
> +interface DemoState {
参考上面 `bignumber` 的方式设置 state，可以避免写 Props 和 State 类型

2024-03-26 11:44 UTC, YSMJ1994 commented on components/number-picker/__docs__/demo/limit/index.tsx
> +function onCorrect(obj: object) {
上面两处需明确类型

2024-03-26 11:44 UTC, YSMJ1994 commented on components/number-picker/__docs__/demo/precision/index.tsx
> +function onCorrect(obj: object) {
`obj` 需明确类型

2024-03-26 11:44 UTC, YSMJ1994 commented on components/number-picker/__docs__/demo/step/index.tsx
> +function onCorrect(obj: object) {
同上

2024-05-30 07:44 UTC, eternalsky commented on components/number-picker/types.ts
> +    defaultValue?: number | string;
这里其实直接 Omit 就可以了

2024-05-30 07:47 UTC, eternalsky commented on components/number-picker/number-picker.tsx
> +        if (isNaN(val as unknown as number)) val = this.state.value;
这个文件里还是有很多调用 isNaN 的地方有强制类型转换

2024-05-31 01:58 UTC, eternalsky requested changes

2024-06-03 11:12 UTC, eternalsky requested changes

2024-06-03 11:12 UTC, eternalsky commented on components/number-picker/__docs__/demo/accessibility/index.tsx
> +    onChange(value: number) {
这里使用箭头函数更好，在传入时 bind react 不推荐，是一种反模式。

2024-06-03 12:51 UTC, eternalsky approved these changes

2024-06-04 02:10 UTC, YSMJ1994 approved these changes

2024-06-04 02:11 UTC, merged