[ConfigProvider] improve config types, close #4751
alibaba-fusion/next pull request #4754
Opened 2024-02-21 09:13 UTC by YSMJ1994

2024-02-21 13:29 UTC, eternalsky requested changes

2024-02-21 13:29 UTC, eternalsky commented on components/config-provider/config.tsx
> +    return ConfigedComponent as unknown as ConfiguredComponentClass<P, RefType> &
这个推断没有考虑 exportNames

2024-02-21 13:31 UTC, eternalsky requested changes

2024-02-21 13:31 UTC, eternalsky commented on components/config-provider/config.tsx
> +>(Component: C, options: ConfigOptions<ComponentPropsWithoutRef<C>, keyof ComponentRef<C>> = {}) {
keyof ComponentRef<C> 改成 Exclude<keyof ComponentRef<C>, symbol> 就可以用于索引了，关键点是 symbol 不能用于索引。

2024-02-21 13:31 UTC, eternalsky commented on components/config-provider/config.tsx
> +                        this[name as string] = field.bind(this._instance);
field.bind returnType 是 any，这里因为 exclude symbol 后不用 as string 也可以用于索引了，但是会有另一个错误，暂时没找到解法。

2024-02-22 02:47 UTC, YSMJ1994 commented on components/typography/types.ts
> +export declare class TitleClass extends Component<TitleProps> {
不定义出来的话，tsc 编译时会自动推断 Title 组件的类型，输出的结果会很复杂不易读

2024-02-22 02:55 UTC, eternalsky commented on components/typography/types.ts
> +export declare class TitleClass extends Component<TitleProps> {
没太懂，只有 Title 会有这个问题？

2024-02-22 04:51 UTC, YSMJ1994 commented on components/typography/types.ts
> +export declare class TitleClass extends Component<TitleProps> {
Title.tsx 里面是一个函数，其返回值是 Title 组件，如果不定义为一个特定类型，会自动将 class Title 推断为一个复杂的类型，可以 build:transform 试一下看看

2024-02-22 06:24 UTC, eternalsky approved these changes

2024-02-22 06:27 UTC, merged