refactor(Drawer): Document optimization & Upgrade testing tools and optimize use cases & rename to ts
alibaba-fusion/next pull request #4760
Opened 2024-02-27 06:12 UTC by luolin-ck

新增功能如下：
TS化;
文档优化;
测试工具升级，用例优化;
close#4582

2024-02-27 06:13 UTC, luolin-ck commented
close #4582

2024-03-12 06:03 UTC, eternalsky commented
npm run check:eslint 还有不少比较好优化的 eslint warning，也一起解决一下吧。

2024-03-12 06:47 UTC, eternalsky requested changes

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/__docs__/demo/placement/index.tsx
> +    onPlacementChange = (dir: string | number | boolean, e: any) => {
e 这里没有用到，看起来可以不写

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/__docs__/demo/basic/index.tsx
> +    onClose = (reason: string, e: React.MouseEvent | KeyboardEvent) => {
这里可以直接使用 DrawerProps['onClose']，DrawerProps 可以通过 import type { DrawerProps } from '@alifd/next/lib/drawer'; 引出。下同

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/__docs__/demo/quick/index.tsx
> +import { QuickShowRet } from '../../../types';
demo 里不要使用相对路径引用 type，参考上面的评论，另这里需要 import  type

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/__docs__/demo/select/index.tsx
> +const onToggleHighlightItem = function (item: any, type: any) {
尽量不要使用 any，这些地方的类型都可以根据上面的评论，从组件 props 类型里指定。

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/__docs__/theme/index.tsx
> +import { InnerProps } from '../../types';
此处与上面相同，不要相对引用，且需要 import type

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/__docs__/theme/index.tsx
> +                placement={placement as InnerProps['placement']}
这个 as 应该放在上面 placement 定义的地方。

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/__tests__/index-v2-spec.tsx
> +        hide();
cy.get 是异步执行的，这里 hide 有可能会优于 cy.get 的实际指令先执行，最好应将其放入 cy.then() 中。

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/drawer-v2.tsx
> +import { DrawerProps } from './types';
import type

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/drawer-v2.tsx
> +            dom.setStyle(wrapperRef.current as HTMLDivElement, 'display', 'none');
这里在上面 useRef 那里已经声明 wrapperRef.current 是 wrapperRef.current，感觉这里应该不需要再 as，这里只可能是因为 wrapperRef.current 是 null，这种应该使用 ！来排除空

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/drawer-v2.tsx
> +        dom.setStyle(wrapperRef.current as HTMLDivElement, 'display', '');
同上

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/drawer-v2.tsx
> +        [className as string]: !!className,
这里也应该是用 ！来删除空值

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/drawer-v2.tsx
> +        [className as string]: !!className,
同上

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/drawer-v2.tsx
> +                                newAnimation as
这里可以直接使用 OverlayAnimate 中关于 animate 的定义，就不需要写这么多了，而且也可以方便后续继承。

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/drawer.tsx
> +import Overlay, { PopupProps } from '../overlay';
type PopupProps

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/drawer.tsx
> +import { DrawerProps } from './types';
import type

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/drawer.tsx
> +         * @param trigger - 关闭触发行为的描述字符串
propTypes 上的注释可以删除了

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/drawer.tsx
> +        closeable:
这里应该直接复用 types 里定义的。

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/drawer.tsx
> +        const others: OthersProps = pickOthers(Object.keys(Drawer.propTypes), this.props);
这里可以直接改成 pickOthers(Drawer.propTypes, this.props)，使用 pickOthers 自身的类型约束就可以推导出 others 了。

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/drawer.tsx
> +                    onClose as (reason: string, e: React.MouseEvent<Element, MouseEvent>) => void
这里的类型转换有点奇怪，为什么不是 onClose 定义的地方解决，而是在这里 as 呢

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/drawer.tsx
> +            animation: this.getAnimation(placement as string),
此处应该是因为 placement 可能为空，应用 ！

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/drawer.tsx
> +            align: this.getAlign(placement as string),
同上

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/drawer.tsx
> +                content={content as string | undefined}
这里的类型转换也很奇怪，是为了排除什么？

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/index.tsx
> +import { DrawerProps, QuickShowRet } from './types';
import type

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/inner.tsx
> +import { InnerProps } from './types';
import type

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/inner.tsx
> +        const ariaProps: object = {
ts 里类型里的 object，和 js 的里 Object 对象不同，这里应直接指定 interface 比较合适

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/inner.tsx
> +                    onClick={onClose as unknown as React.MouseEventHandler}
这里为什么要强制类型转换？

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/inner.tsx
> +            [className as string]: !!className,
同之前评论

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/inner.tsx
> +        const ariaProps: object = {
同之前评论

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/show.tsx
> +import { DrawerProps } from './types';
import type

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/show.tsx
> +    // eslint-disable-next-line
这里应该 disable 具体的规则，而不是全部 disable

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/show.tsx
> +    let instance: ModalInstance | null = null,
这里定义错误，myRef  应为 InstanceType<typeof ConfigModal>，instance 同 myRef

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/show.tsx
> +                    myRef = ref as unknown as Modal;
上面定义好后，这里就不需要强制类型转换了。

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/show.tsx
> +            instance = myRef as unknown as ModalInstance;
同上

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/show.tsx
> +    WrappedComponent: React.ComponentType<P>
React.ComponentType 并不是唯一一种可以用来生成 ReactElement 的，这里建议参考一下 Dialog pr 里的处理方式。https://github.com/alibaba-fusion/next/pull/4772

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/types.ts
>       * [废弃]同closeMode, 控制对话框关闭的方式，值可以为字符串或者布尔值，其中字符串是由以下值组成：
较长的部分应该写在 @remarks 中，参考 https://github.com/alibaba-fusion/next/pull/4772

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/types.ts
> +export interface DrawerProps
这里应该有注释 @api Drawer 参考一下文档。

2024-03-12 06:47 UTC, eternalsky commented on components/drawer/types.ts
> +        CommonProps {
整个文档优化没有做，相应的 tag 没有添加，可以再看一下文档，并参考一下 https://github.com/alibaba-fusion/next/pull/4772

2024-03-12 06:47 UTC, eternalsky commented on components/overlay/index.d.ts
> +    static propTypes: object;
这里感觉没有必要。

2024-03-12 06:47 UTC, eternalsky commented on package-lock.json
> +}
这里还是有 diff

2024-03-19 08:54 UTC, eternalsky commented
close #3748

2024-03-19 12:25 UTC, eternalsky requested changes

2024-03-19 12:25 UTC, eternalsky commented on components/drawer/types.ts
> +     */
v2 专属和 v2 废弃的 API，可以参考 Dialog 的 pr，https://github.com/alibaba-fusion/next/pull/4772/files#diff-b129089a7edccf3fa2c37fc01a2ee9cf5f313416a241a290236d6936f578ec13R15 。区分为 V1 和 V2 的 props，这样有两个好处，首先如果用户没开启 v2，那 v2 废弃的那些 prop 不应该是 deprecated 掉的。另外有些 prop 是 v2 才有，和在一起的话，会给出 v1 也有的假想。

2024-03-20 12:13 UTC, eternalsky requested changes

2024-03-20 12:13 UTC, eternalsky commented on components/drawer/types.ts
> +    v2?: boolean;
这里 v2 应该是 true

2024-03-20 12:13 UTC, eternalsky commented on components/drawer/types.ts
> +     * @deprecated v2 废弃 - v2 deprecated
v1 props 里应该不包含 @deprecated

2024-03-21 03:07 UTC, eternalsky approved these changes

2024-03-21 03:14 UTC, merged