feat(TreeSelect): support useDetailValue, close #3531
alibaba-fusion/next pull request #4771
Opened 2024-03-06 07:46 UTC by YSMJ1994

2024-03-06 11:08 UTC, eternalsky requested changes

2024-03-06 11:08 UTC, eternalsky commented on components/tree-select/tree-select.jsx
> +        const { useDetailValue, onChange } = this.props;
这里主要是 onChange 出去可以用 detailValue，但是好像没看到 value 是 detailValue 时做的适配？

2024-03-06 11:23 UTC, eternalsky requested changes

2024-03-06 11:23 UTC, eternalsky commented on components/tree-select/__docs__/demo/use-detail-value/index.tsx
> +                defaultValue="2"
这里也应该是 detailValue 了

2024-03-06 11:23 UTC, eternalsky commented on components/tree-select/__docs__/demo/use-detail-value/index.md
> +# zh-CN order=8
demo 是技术升级之后的，其他都是技术升级之前的。这样也可以支持吗

2024-03-06 12:00 UTC, YSMJ1994 commented on components/tree-select/__docs__/demo/use-detail-value/index.md
> +# zh-CN order=8
现在全部 demo 都是升级后的了，都用脚本转换过来了

2024-03-07 02:53 UTC, YSMJ1994 commented on components/tree-select/tree-select.jsx
> +        const { useDetailValue, onChange } = this.props;
这里的 data就是 detailValue，直接用就行了

2024-03-07 03:36 UTC, eternalsky approved these changes

2024-03-07 03:41 UTC, merged