feat(Select): selected option Tag suport colorful set with dataSource
alibaba-fusion/next pull request #4777
Opened 2024-03-13 07:37 UTC by seven-lh

#3778

2024-03-19 03:16 UTC, eternalsky requested changes

2024-03-19 03:16 UTC, eternalsky commented on components/select/__docs__/demo/multiple colorful tag/index.md
> +# zh-CN order=2
目录名字调整一下，不要直接用空格连接单词，参考其他的 demo

2024-03-19 03:16 UTC, eternalsky commented on components/select/scss/mixin.scss
> -    padding-top: $padding-tb;
这里为什么删除了两个padding 样式？

2024-03-19 06:06 UTC, seven-lh commented on components/select/scss/mixin.scss
> -    padding-top: $padding-tb;
padding  上下是为了垂直居中 标签模式下这两个padding导致标签下沉了

2024-03-20 01:58 UTC, eternalsky requested changes

2024-03-20 01:58 UTC, eternalsky commented on components/select/__tests__/index-spec.js
> +describe('issue', function() {
这个感觉不是一个 issue，issue 应该是用来跟踪 bug 的。这个明显是一个 feature

2024-03-20 02:47 UTC, seven-lh commented on components/select/__tests__/index-spec.js
> +describe('issue', function() {
已修正

2024-03-20 09:15 UTC, eternalsky approved these changes

2024-03-20 09:16 UTC, merged