refactor(Tree): ts & docs & test tools
alibaba-fusion/next pull request #4779
Opened 2024-03-15 03:45 UTC by zizairufengLT

close #4619

2024-03-15 09:38 UTC, eternalsky commented
rename to ts 按照文档，应该单独提一个 commit，后面可以注意一下。

2024-03-15 09:40 UTC, eternalsky commented
引用类型时需要 import type，可以先 rebase 一下 master，然后 npm run check:eslint tree 去检查一下哪里该 import type 的地方，没有 import

2024-03-22 01:50 UTC, eternalsky requested changes

2024-03-22 01:53 UTC, eternalsky requested changes

2024-03-22 01:53 UTC, eternalsky commented on components/tree/__docs__/demo/draggable/index.tsx
> +import type { DataNode } from '../../../types';
demo 里不要出现相对路径，这里可以参考上面的评论中引入 type 的方式

2024-03-22 01:53 UTC, eternalsky commented on components/tree/__docs__/demo/search-tree/index.tsx
> +import type { DataNode, NodeInstance } from '../../../types';
此处同上，后续相同问题类似处理，不再赘述

2024-03-22 08:10 UTC, zizairufengLT commented on components/tree/__tests__/index-spec.tsx
> +        let dragObj: DataNode = { key: dragKey };
这里不赋值的话，下面会报`Variable 'dragObj' is used before being assigned.ts(2454)`，ts-expect-error 解决掉么？

2024-03-22 08:52 UTC, zizairufengLT commented on components/tree/__tests__/index-spec.tsx
> +                    if (nodes.filter(node => !node.props.children).length !== nodes.length) {
去掉这个是因为现在补上类型后，children.length 会报错，所以去掉了

2024-03-22 09:06 UTC, zizairufengLT commented on components/tree/view/tree-node.tsx
> +        const target = e.target as HTMLInputElement;
因为React.KeyboardEvent<HTMLInputElement>这个并不会推断出e.target 有HTMLInputElement类型

2024-03-25 02:22 UTC, eternalsky commented on components/tree/__tests__/index-spec.tsx
> +        let dragObj: DataNode = { key: dragKey };
这里的原因是因为 DataNode 是一个接口，目前的逻辑上来看，dragObj 并不一定在后面的  loop 中能得到值，但实际上应该是必然能拿到。因此这里通过类型，在不修改逻辑的情况下，最好的改法，应该是 let dragObj: DataNode | undefined，然后下面通过 ！强调其必有值。

2024-03-25 02:26 UTC, eternalsky commented on components/tree/__tests__/index-spec.tsx
> +                    if (nodes.filter(node => !node.props.children).length !== nodes.length) {
没有 children 和 children 为 0 意思还是很不一样的，报错这里是测试 case，在这个 case 的情况下，倒是勉强可以

2024-03-26 08:51 UTC, zizairufengLT commented on components/tree/__tests__/index-spec.tsx
> +    // should improve this case
因为这个测试用例我的理解下是有问题的，然后VirtualList组件的TC还未完善，想等待完善后这里再补充

2024-03-26 12:09 UTC, eternalsky requested changes

2024-03-26 12:09 UTC, eternalsky commented on components/tree/view/tree-node.tsx
> +            tabIndex: number;
这里可以直接 tabIndex expect error

2024-03-28 03:14 UTC, eternalsky requested changes

2024-03-28 03:14 UTC, eternalsky commented on components/tree/view/tree.tsx
> +        this.virtualListRef = React.createRef();
上面定义了 createRef ，但下面用的是 React.createRef ，导致上面的没用上。

2024-03-28 03:43 UTC, eternalsky approved these changes

2024-03-28 03:43 UTC, merged