refactor(Transfer): rename to ts & upgrade document & refactor unit testing
alibaba-fusion/next pull request #4783
Opened 2024-03-18 12:50 UTC by wangw11056

closes #4618

2024-03-27 03:12 UTC, YSMJ1994 requested changes
1. demo 用于给用户提供该组件某场景用法示例，要求在单文件里提供完整的使用示例，不能抽象一些通用逻辑然后通过相对路径的方式复用
2. 合并一下 master，然后执行 `npm run check transfer` 命令，根据提示修改代码

2024-03-27 03:12 UTC, YSMJ1994 commented on components/transfer/view/transfer-item.tsx
> +    removeHighlightTimer: NodeJS.Timer;
NodeJS.Timer 是 node 环境的setTimeout 返回值类型，而这里是 web 运行环境，应该是 number 类型，但考虑到目前项目全局ts类型未隔离 node，所以这里可以用 `ReturnType<typeof setTimeout>` 来作为类型

2024-03-28 07:26 UTC, eternalsky commented on components/transfer/view/transfer-item.tsx
> +    removeHighlightTimer: NodeJS.Timer;
这里还有一个办法，就是 setTImeout ，改成 window.setTimeout

2024-04-15 07:11 UTC, YSMJ1994 commented on components/transfer/__docs__/demo/accessibility/index.tsx
> +class Demo extends React.Component<TransferProps> {
这里定义 props 类型是没有意义的，下面其它的 demo 也调整一下

2024-04-15 07:11 UTC, YSMJ1994 commented on components/transfer/__docs__/demo/custom-panel/index.tsx
> +                                    ).map(item => item.props.value);
这里的类型定义是没有必要的，需要定位一下 treeNodeProps 里面 为何没有 value的问题原因，看看是否要做出调整

2024-04-17 07:26 UTC, wangw11056 commented on components/transfer/view/transfer-panel.tsx
> +                (this.list as HTMLDivElement).scrollTop = 0;
其实这里我本来想改逻辑，例如：'scrollTop' in this.list && this.list.scrollTop > 0

2024-05-06 03:22 UTC, YSMJ1994 commented on components/transfer/view/transfer.tsx
> +    constructor(props: TransferProps, context: unknown) {
这里要么去掉 context，要么加上 `context?: unknown`，否则 ConfigProvider.config 推断结果不正确

2024-05-06 03:22 UTC, YSMJ1994 commented on components/transfer/__docs__/demo/custom-panel/index.tsx
> +                }) => {
这里的类型定义是多余的，应该由 Transfer props.children 来定义约束

2024-05-06 03:22 UTC, YSMJ1994 commented on components/transfer/__docs__/demo/custom-panel/index.tsx
> +                                    ).map(item => item.props.value);
此处仍未处理 `value does not exist on  item.props ` 的问题

2024-05-06 03:23 UTC, YSMJ1994 requested changes
运行 `npm run check transfer` 有很多错误，需要解决一下

2024-05-07 08:49 UTC, YSMJ1994 commented on components/transfer/view/transfer-panel.tsx
> +        const { prefix, title, showSearch, filter, dataSource = [] } = this.props;
这里不应修改原逻辑，dataSource 有默认值，下面直接 ! 断言即可

2024-05-30 02:38 UTC, merged