Upgrade/radio
alibaba-fusion/next pull request #4794
Opened 2024-03-22 07:37 UTC by YSMJ1994

2024-04-02 08:09 UTC, eternalsky requested changes

2024-04-02 08:09 UTC, eternalsky commented on components/radio/radio-group.tsx
> +interface GroupState {
GroupState 需要输出，否则构建会出错

2024-04-02 08:09 UTC, eternalsky commented on components/radio/with-context.tsx
> +    return WrappedComp as unknown as typeof WrappedRadio;
这里有必要做强制类型转换吗？看起来不转换构建也可以正常推导。

2024-04-03 02:28 UTC, YSMJ1994 commented on components/radio/with-context.tsx
> +    return WrappedComp as unknown as typeof WrappedRadio;
1. 在 radio-group 里面需要用到这个推断出来的类型
2. 自动推断的话，会生成一个很复杂的类型，不太易读，可以build试一下

2024-04-03 02:46 UTC, eternalsky commented on components/radio/with-context.tsx
> +    return WrappedComp as unknown as typeof WrappedRadio;
1 的话，RadioGroup 里已经引入了 Radio 了，为什么不直接用 typeof Radio 而需要额外定义一个 WrappedRadio 呢。

2024-04-03 03:40 UTC, YSMJ1994 commented on components/radio/with-context.tsx
> +    return WrappedComp as unknown as typeof WrappedRadio;
因为那个地方获得的 ref 对象确实是这个 withContext 返回的类，而非 Radio组件本身

2024-04-03 06:15 UTC, eternalsky commented on components/radio/with-context.tsx
> +    return WrappedComp as unknown as typeof WrappedRadio;
> 因为那个地方获得的 ref 对象确实是这个 withContext 返回的类，而非 Radio组件本身

Radio 本身就已经是被 withContext 包裹之后再导出的了。

2024-04-03 06:16 UTC, eternalsky commented on components/radio/radio-group.tsx
>  import Radio from './radio';
这里 import default，引入的已经是被 withContext 包裹之后的 Radio 了

2024-04-09 09:30 UTC, eternalsky approved these changes

2024-04-09 09:32 UTC, merged