feat(CascaderSelect): should support empty search value after selecti…
alibaba-fusion/next pull request #4806
Opened 2024-03-28 02:17 UTC by YunMeng99

…on close #3008

2024-06-11 07:18 UTC, eternalsky requested changes

2024-06-11 07:18 UTC, eternalsky commented on components/cascader-select/cascader-select.jsx
> +            if(clearSearchOnSelect && searchValue){
这里和 703 行对于 searchValue 的处理逻辑为什么是分开的，并且还不一样？

2024-06-11 07:19 UTC, eternalsky commented on components/cascader-select/cascader-select.jsx
> +            if(clearSearchOnSelect && searchValue){
另外格式化的问题也解决一下哈

2024-06-12 10:03 UTC, YunMeng99 commented on components/cascader-select/cascader-select.jsx
> +            if(clearSearchOnSelect && searchValue){
已修改

2024-06-20 10:10 UTC, eternalsky requested changes

2024-06-20 10:10 UTC, eternalsky commented on components/cascader-select/__tests__/issue-spec.tsx
> +        cy.get('.next-cascader > .next-cascader-inner').should('not.be.empty');
这里应该还要断言一下 input 的 value 也是空了的。
另外这个 tc 其实对应的是一个 feature，放在 index-spec 里会更好一点。

2024-06-27 07:43 UTC, merged