Fix issue 4593
alibaba-fusion/next pull request #4807
Opened 2024-03-29 01:51 UTC by Yuchaocheng

2024-05-14 12:03 UTC, eternalsky requested changes

2024-05-14 12:03 UTC, eternalsky commented on components/message/index.tsx
> +export type ContextMessage = typeof toast;
这个类型的导出感觉没有必要，typeof 是很容易得的。

2024-05-14 12:03 UTC, eternalsky commented on components/message/message.tsx
> +    static show: Toast['show'];
这里其实没必要再这里多定义一遍，可以考虑在 index.tsx 中使用 assignSubComponent 进行输出。

2024-05-21 02:26 UTC, Yuchaocheng commented on components/message/toast.tsx
> +export const withContext = <T extends object>(WrappedComponent: React.ComponentType<T>) => {
如果把 demo 里 withContext 改成直接查看，会影响到其他使用Message.show等函数式调用的demo。这些demo会取withContext中的根ConfigProvider的context，造成样式问题。

2024-05-30 03:06 UTC, eternalsky commented on components/message/toast.tsx
> +type ConfigMask = InstanceType<typeof NewMask> | null;
ConfigMask 里感觉不应该包含 null，null 应该是在下面和 ConfigMask 并列

2024-05-30 03:06 UTC, eternalsky commented on components/message/toast.tsx
> +export const withContext = <T extends object>(WrappedComponent: React.ComponentType<T>) => {
> 如果把 demo 里 withContext 改成直接查看，会影响到其他使用Message.show等函数式调用的demo。这些demo会取withContext中的根ConfigProvider的context，造成样式问题。

你的意思是影响其他 demo？

2024-05-30 03:08 UTC, eternalsky requested changes

2024-05-30 03:08 UTC, eternalsky commented on components/message/__docs__/index.md
> -```js
这部分没有了

2024-05-30 03:17 UTC, eternalsky requested changes

2024-05-30 03:17 UTC, eternalsky commented on components/message/message.tsx
> +    static config: (config: MessageConfig) => void;
这四个类方法还是看不懂，如果是外面赋值的，那应该都是放在 assignSubComponents 里的，如果不是，这里又指给了类型没有实现。另外 open 下面那三个确定一下是成员方法还是类方法？

2024-05-30 03:21 UTC, Yuchaocheng commented on components/message/toast.tsx
> +export const withContext = <T extends object>(WrappedComponent: React.ComponentType<T>) => {
是的，其他demo里只要使用了函数式调用就会被影响

2024-06-06 12:46 UTC, eternalsky requested changes

2024-06-06 12:46 UTC, eternalsky commented on components/message/message.tsx
> +import toast2, { type MessageConfig } from './toast2';
这里还有个可修复的 lint 问题

2024-06-07 03:03 UTC, merged