refactor(Select): improve ts, doc and tc
alibaba-fusion/next pull request #4809
Opened 2024-04-02 01:57 UTC by eternalsky

2024-04-11 12:44 UTC, YSMJ1994 requested changes
1. 是否可以用 `ClassPropsWithDefault ` 方案，避免太多的有 default 的 props 的 `!` 断言
2. build会有一些 ts 错误

2024-04-11 12:44 UTC, YSMJ1994 commented on components/select/util.ts
> +): {
这里的 `mapValueDS`、`mapMenuDS` 应该是可以为 undefined 的，我看其他很多地方加了 `!` 断言，应该是没有必要的

2024-04-11 12:44 UTC, YSMJ1994 commented on components/select/select.tsx
> +    handleSelectAll(e: UIEvent<HTMLElement>) {
应是 `React.MouseEvent<HTMLDivElement>`

2024-04-11 12:44 UTC, YSMJ1994 commented on components/select/select.tsx
> +            const selectedValueNodes = detailedValueArr.map(v => {
这里的调整跟 `788` 行会有一些难以理解

2024-04-11 12:44 UTC, YSMJ1994 commented on components/select/select.tsx
> +    handleArrowClick = (e: UIEvent<HTMLElement>) => {
这里类型应是 `React.MouseEvent<HTMLSpanElement>`

2024-04-11 12:44 UTC, YSMJ1994 commented on components/select/select.tsx
> +    handleClear = (e: UIEvent<HTMLElement>) => {
这里类型应是 `React.MouseEvent<HTMLSpanElement> |  React.KeyboardEvent<HTMLInputElement>`

2024-04-11 12:44 UTC, YSMJ1994 commented on components/select/select.tsx
> +     * @param props -
可移除

2024-04-11 12:44 UTC, YSMJ1994 commented on components/select/select.tsx
> +            (locale!.selectPlaceHolder as string);
这里代表 props.locale 类型未明确，参考一下`Tag` 组件

2024-04-11 12:44 UTC, YSMJ1994 commented on components/select/select.tsx
> -                    aria-valuetext={valuetext}
这个为啥移除了

2024-04-11 12:44 UTC, YSMJ1994 commented on components/select/select.tsx
> +     * @param props -
可移除

2024-04-11 12:44 UTC, YSMJ1994 commented on components/select/index.tsx
> +        transform: /* istanbul ignore next */ (props, deprecated) => {
这里的注释可以移除

2024-04-11 12:44 UTC, YSMJ1994 commented on components/select/index.tsx
> +function transform(props: Record<string, unknown>, deprecated: PropsDeprecatedPrinter) {
这里 props 类型不应泛化

2024-04-12 02:31 UTC, eternalsky commented on components/select/select.tsx
> +    handleSelectAll(e: UIEvent<HTMLElement>) {
> 应是 `React.MouseEvent<HTMLDivElement>`

如果从谁触发的角度来看是这个，但是从这个函数自身来讲，他只需要是个 UIEvent 即可，既然函数要求没有这么苛刻，那他的类型应该是从自身实现触发，而不是调用者的角度出发来看的，下方类似问题也是一样。

2024-04-12 02:55 UTC, eternalsky commented on components/select/select.tsx
> +                    aria-expanded={this.state.visible ? 'true' : 'false'}
> 好像直接传递 `this.state.visible` 也可以

这里如果传入 false 的话，实际的渲染效果里 dom 上的 aria-expanded 不是 'false'，而是不渲染这个 attr，这与预期不符，并且过不了 aria 测试。

2024-04-12 03:01 UTC, eternalsky commented on components/select/select.tsx
> -                    aria-valuetext={valuetext}
> 这个为啥移除了

https://www.w3.org/TR/wai-aria-1.1/#aria-valuetext aria-valuetext 不适用于 role=combobox，加的话通过不了 aria 测试。且 aria-valuetext 必须和 aria-valuenow 配合使用，适用于值和实际可阅读要区分的情况，对于 input 来说，他的值本来就是可读的，因此这里也没有 aria-valuetext 存在的必要。

2024-04-12 03:16 UTC, eternalsky commented on components/select/select.tsx
> +            const selectedValueNodes = detailedValueArr.map(v => {
不太明白，这里几乎没有调整，逻辑和原来基本是已知的，只是在 if 的第一行用了一个赋值来完成类型的指定，否则后面的 value 都需要 as ObjectItem[]

2024-04-12 03:26 UTC, eternalsky commented
> 1. 是否可以用 `ClassPropsWithDefault ` 方案，避免太多的有 default 的 props 的 `!` 断言
> 2. build会有一些 ts 错误

build ts 错误已解决。
Select 大量采用基类继承的方式来扩展组件，使用 ClassPropsWithDefault 定义 props 会使得扩展层变的很麻烦，有些问题不好解决。另外使用 ！的地方不多，我觉得在可接受的范围内。

2024-04-15 07:48 UTC, YSMJ1994 commented on components/select/select.tsx
> +     * @param props -
这里没有调整

2024-04-15 07:51 UTC, YSMJ1994 approved these changes

2024-04-15 08:52 UTC, merged