refactor(Calendar): rename to ts, improve ts, doc and tc, close #4569
alibaba-fusion/next pull request #4818
Opened 2024-04-08 10:10 UTC by eternalsky

2024-05-07 03:25 UTC, YSMJ1994 requested changes

2024-05-07 03:25 UTC, YSMJ1994 commented on components/calendar/types.ts
> +    onModeChange?: (mode: string) => void;
这里的 mode 参数类型可以精确为 `CalendarMode`

2024-05-07 03:25 UTC, YSMJ1994 commented on components/calendar/table/month-table.tsx
> +                const isSelected = isSameMonth(monthDate, value!);
isSameMonth 应该是支持 value 为 null 的，这里的断言可以去掉

2024-05-07 03:25 UTC, YSMJ1994 commented on components/calendar/table/month-table.tsx
> +    );
从代码来看，selectedDate 参数支持 null 类型

2024-05-07 03:25 UTC, YSMJ1994 commented on components/calendar/table/date-table.tsx
> +function isSameDay(a: Moment, b: Moment) {
从代码来看，参数应该都支持 null 类型

2024-05-07 03:25 UTC, YSMJ1994 commented on components/calendar/table/date-table.tsx
> +                    (isSameDay(currentDate, startValue!) || isSameDay(currentDate, endValue!)) &&
isSameDay 应支持传递 null 参数，这里的断言是多余的

2024-05-07 03:25 UTC, YSMJ1994 commented on components/calendar/range-calendar.tsx
> +            prevMode: props.mode!,
这里会有点困惑，mode为何与 prevMode 类型不一致，然后这里一个加断言一个不加

2024-05-07 03:25 UTC, YSMJ1994 commented on components/calendar/head/year-panel-header.tsx
> +        const start = parseInt((year / 10).toString(), 10) * 10;
这里不要修改实现，用 ts-expect-error 来暴露问题

2024-05-07 03:25 UTC, YSMJ1994 commented on components/calendar/table/year-table.tsx
> +                            title={title as string}
这里应跟上面一样用 ts-expect-error 标注即可

2024-05-07 12:35 UTC, eternalsky commented on components/config-provider/config.tsx
> +    type ComponentPropsWithoutRef,
这里没太看懂

2024-05-08 06:25 UTC, YSMJ1994 approved these changes

2024-05-08 06:25 UTC, merged