refactor(Progress): rename to ts, improve ts, doc and tc
alibaba-fusion/next pull request #4827
Opened 2024-04-25 03:50 UTC by Yuchaocheng

2024-04-29 12:16 UTC, eternalsky requested changes

2024-04-29 12:16 UTC, eternalsky commented on components/progress/__docs__/demo/controlled/index.tsx
>          this.state = {
这里可以把 state 从 constructor 里挪出来，就不用额外去定义 props 和 state 的 interface 了。

2024-04-29 12:16 UTC, eternalsky commented on components/progress/__docs__/theme/index.tsx
> +/* eslint-disable */
这里的无用注释可以去掉。

2024-04-29 12:16 UTC, eternalsky commented on components/progress/__tests__/index-spec.tsx
> +/* eslint-disable no-undef, react/jsx-filename-extension */
这个注释可以去掉

2024-04-29 12:16 UTC, eternalsky commented on components/progress/__tests__/index-spec.tsx
> +            cy.get<MountReturn>('@progress').then(({ component, rerender }) => {
这里可以简化为使用 cy.rerender，可以参考一下其他的 tc 里的示例。

2024-04-29 12:16 UTC, eternalsky commented on components/progress/__tests__/index-spec.tsx
> +                const pathEl = $element[0] as unknown as SVGPathElement;
这里必须先转换为 unknown 做强制转换吗

2024-04-29 12:16 UTC, eternalsky commented on components/progress/types.ts
> +export type ProgressLineProps = Omit<ProgressProps & DefaultProgressProps, 'shape'>;
这里的实现可以参考其他组件里的 ClassPropsWithDefault 的用法

2024-05-05 02:32 UTC, Yuchaocheng commented on components/progress/__docs__/demo/controlled/index.tsx
>          this.state = {
提出来是可以的，但是如果不传入state的类型，setState以函数参数调用时，prevState的类型无法正确推断

2024-05-05 03:11 UTC, Yuchaocheng commented on components/progress/__tests__/index-spec.tsx
> +                const pathEl = $element[0] as unknown as SVGPathElement;
是的，$element[0]为 HTMLElement类型，它和SVGPathElement无兼容关系。不过他们有共同的父元素Element。这里我改一下先转为Element类型。关于svg类型的不继承于HTMLElement可以看这个[#4551](https://github.com/facebook/flow/pull/4551)

2024-05-30 03:29 UTC, eternalsky approved these changes

2024-05-30 03:29 UTC, merged