refactor(TreeSelect): ts & docs & test tools
alibaba-fusion/next pull request #4837
Opened 2024-05-08 03:38 UTC by zizairufengLT

close #4620

2024-05-14 03:01 UTC, eternalsky commented on components/tree-select/__tests__/index-spec.tsx
> +        cy.get<MountReturn>('@Demo').then(({ component, rerender }) => {
此处同上

2024-05-14 03:06 UTC, eternalsky commented on components/tree-select/tree-select.tsx
> +            const posArr = (pos as string).split('-');
这里为什么需要 as string？

2024-05-14 03:10 UTC, eternalsky commented on components/tree-select/tree-select.tsx
> +        const loop = (children: React.ReactNode, prefix = '0') =>
这里建议都 import {type ReactNode} from 'react' 去使用，其他地方同，types 里不需要，

2024-05-14 03:11 UTC, eternalsky commented on components/tree-select/tree-select.tsx
> +        } as TreeSelectState;
这里为什么需要 as 强制转换一下？

2024-05-14 03:12 UTC, eternalsky commented on components/tree-select/tree-select.tsx
> +            // @ts-expect-error should change logic
这个错误的原因说的不是很清楚，应该说明具体的原因。下同

2024-05-14 03:12 UTC, eternalsky commented on components/tree-select/tree-select.tsx
> +        return (value as Key[]).reduce((ret, v) => {
value 既然上面已经指定过类型了，为什么下面又要立刻转换类型，看不懂。

2024-05-14 03:13 UTC, eternalsky commented on components/tree-select/tree-select.tsx
> +            this.state._k2n as unknown as KeyEntities,
这里为什么要强制类型转换？

2024-05-14 03:13 UTC, eternalsky commented on components/tree-select/tree-select.tsx
> +                    this.state._k2n as unknown as KeyEntities,
同上

2024-05-14 03:13 UTC, eternalsky commented on components/tree-select/tree-select.tsx
> +                    this.state._k2n as unknown as KeyEntities,
同上

2024-05-14 03:14 UTC, eternalsky commented on components/tree-select/tree-select.tsx
> +                    d.disabled = disabled || (checkboxDisabled as boolean);
checkboxDisabled 为什么需要 as boolean？

2024-05-14 03:16 UTC, eternalsky commented on components/tree-select/tree-select.tsx
> +            const removedPos = this.state._v2n[removedValue as string].pos as string;
pos  as  string 的地方太多了，为什么不从源头指定好 pos 就是 string 呢

2024-05-14 03:18 UTC, eternalsky commented on components/tree-select/types.ts
> +export type Key = string;
Key 如果就是 string，感觉好像定义没有什么意义。

2024-05-17 06:41 UTC, zizairufengLT commented on components/tree-select/types.ts
> +export type Key = string;
我的想法：
1. Key 更有语义
2. 后续扩展功能，Key 的类型可能变动，统一这里改下就行

2024-05-17 12:43 UTC, zizairufengLT commented on components/tree-select/tree-select.tsx
> +            this.state._k2n as unknown as KeyEntities,
因为getAllCheckedKeys这个方法是 Tree 那边的，两边的KeyEntities 不同

2024-05-20 02:23 UTC, zizairufengLT commented on components/tree-select/tree-select.tsx
> +        const loop = (children: React.ReactNode, prefix = '0') =>
我把 default import 删除了，这样 React.ReactNode 只会引用 react types

2024-05-20 02:29 UTC, zizairufengLT commented on components/tree-select/tree-select.tsx
> +            // @ts-expect-error should change logic
这块主要是 state 被重复赋值了，考虑到这块涉及到代码的改动，暂时先 expect

2024-05-31 01:57 UTC, eternalsky requested changes

2024-05-31 01:57 UTC, eternalsky commented on components/tree-select/types.ts
> +type A<T> = ObjectItem & BasicDataNode & T;
这里有个多余定义的 A

2024-05-31 01:57 UTC, eternalsky commented on components/tree-select/types.ts
> +export interface TreeSelectDataType extends ObjectItem, BasicDataNode {
感觉叫 TreeSelectDataItem  更好一点，因为 DataType = TreeSelectDataItem[] 而且从命名习惯上来说 Next 里的类型都不会带上 Type

2024-05-31 01:57 UTC, eternalsky commented on components/tree-select/types.ts
> +export interface DataNode extends ObjectItem, BasicDataNode {
DataNode  和 TreeSelectDataType  的区别和关系是？看两个都是继承 ObjectItem, BasicDataNode，但是 key 有所不同

2024-05-31 02:05 UTC, zizairufengLT commented on components/tree-select/types.ts
> +export interface DataNode extends ObjectItem, BasicDataNode {
1. 前者是组件内部所用的数据节点，后者是暴露出去的 api 
2. api 的 kwy 属性是可选的，而传递给 Tree 的是必须的

2024-06-03 02:46 UTC, eternalsky approved these changes

2024-06-03 02:47 UTC, merged