Upload  typeScript
alibaba-fusion/next pull request #4841
Opened 2024-05-13 08:56 UTC by FairyYang

2024-05-29 09:45 UTC, eternalsky requested changes

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/base/index.tsx
> +function beforeUpload(info: any) {
此处同上，应用 UploadProps 指定类型

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/beforeupload/index.tsx
> +function beforeUpload(file: any, options: any) {
同上

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/crop/index.tsx
> +// @ts-expect-error 无法解决的问题
无法解决的问题不要 expect-error 找我讨论，expect-error 只用于明显的使用错误造成的类型不对，标记是为了后续好修改。

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/crop/index.tsx
> +    // @ts-expect-error 类型错误
此处同上

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/crop/index.tsx
> +    // @ts-expect-error 类型错误
此处同上

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/crop/index.tsx
> +    uploader: any;
尽量不使用 any，比如这里明显可以不是 any。demo 是给用户看的，不要给用户我们就是 anyScript 的错觉

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/crop/index.tsx
> +        const file = dataURL2Blob2File(data, 'test.png') as unknown as Array<any>;
同上不要出现 as unknown

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/crop/index.tsx
> +                    <img src={this.state.img as unknown as string} style={{ width: 100 }} />
同上

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/data/index.tsx
> +function beforeUpload(info: any) {
同上，类型使用 UploadProps

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/directory/index.tsx
> +function onChange(info: any) {
同上

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/dragger/index.tsx
> +function handleClick(e: React.MouseEvent) {
这里最好是从 React 中解构出来

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/dragger/index.tsx
> +function onDragOver() {
同上

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/extra/index.tsx
> +const showImg = (url: string) => {
同上

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/image/index.tsx
> +function beforeUpload(info: any) {
同上

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/limit/index.tsx
> +            // @ts-expect-error 类型兼容错误
同上

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/limit/index.tsx
> +const onError = (file: File, fileList: File[]) => {
同上

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/maxsize/index.tsx
> +                    // @ts-expect-error  closable属性不存在
同上

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/maxsize/index.tsx
> +            // @ts-expect-error reader.result类型不匹配
同上

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/oss/index.tsx
> +import { ObjectFile } from '../../../types';
这些 changed 的 warning 都处理一下哈~

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/oss/index.tsx
> +    beforeUpload = (file: { tempUrl: string }, options: { action: string; data: any }) => {
同上，使用 UploadProps

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/oss/index.tsx
> +                // @ts-expect-error 类型不兼容
同上

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/oss/index.tsx
> +                // @ts-expect-error 类型不兼容
同上

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/paste/index.tsx
> +        // @ts-expect-error Upload中有selectFiles方法，但是此处报错，怀疑是@alifd/next版本低的问题
这怎么可能呢？我们自己就是 alifd/next，在 demo 里是指向 src 的

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/paste/index.tsx
> +    onChange = (value: any) => {
同上

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/paste/index.tsx
> +                    // @ts-expect-error onPaste属性不存在
同上

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/paste/index.tsx
> +                    // @ts-expect-error 此处的ref期望seveUploaderRef的入参是InstanceType<typeof Upload>，但是实际上是 { getInstance: () => InstanceType<typeof Upload> }
Upload  被 ConfigProvider.config 包裹后本来就是有 getInstance 的。这个 expect error 没看懂

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/submit/index.tsx
> +        this.uploaderRef = ref?.getInstance?.();
上面已经做了 ref 为空的类型守卫，下面 ref 为什么还需要 ？，getInstance 也应该是必有的

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/submit/index.tsx
> +    beforeUpload(info: any, options: any) {
同上

2024-05-29 09:45 UTC, eternalsky commented on components/upload/__docs__/demo/text/index.tsx
> +function beforeUpload(info: any) {
同上

2024-06-20 03:23 UTC, eternalsky commented on components/upload/__docs__/demo/crop/index.tsx
> +                    <img src={this.state.img as string} style={{ width: 100 }} />
这个 img 本来就是 string 吧

2024-06-20 03:23 UTC, eternalsky commented on components/upload/__docs__/demo/extra/index.tsx
> +                    showImg(file.url as string);
同上，判空用 ！。其他类似的地方可以都看一下

2024-06-20 03:23 UTC, eternalsky commented on components/upload/__docs__/demo/extra/index.tsx
> +                    onClick={() => showImg(file.url as string)}
同上

2024-06-20 03:23 UTC, eternalsky commented on components/upload/__docs__/demo/maxsize/index.tsx
> +            img.src = reader.result as string;
判空问题同上

2024-06-20 03:23 UTC, eternalsky commented on components/upload/__docs__/demo/submit/index.tsx
> +        this.uploaderRef = ref?.getInstance?.();
这个还没改

2024-06-20 06:53 UTC, eternalsky requested changes

2024-06-20 06:53 UTC, eternalsky commented on components/upload/__tests__/card-spec.tsx
> +            cy.mount(<CardUpload value={files} />);
这里按照意思应该是重新渲染，而不是重新 mount。这里应该用 cy.rerender 可以参考一下其他组件类似的用法

2024-06-20 06:53 UTC, eternalsky commented on components/upload/__tests__/card-spec.tsx
> +            cy.mount(<CardUpload value={files} showDownload={false} />);
此处同上

2024-06-20 06:53 UTC, eternalsky commented on components/upload/__tests__/card-spec.tsx
> +            cy.mount(<CardUpload value={files} showDownload={false} />);
后续类似 rerender 都同上，不再赘述了哈

2024-06-20 06:53 UTC, eternalsky commented on components/upload/__tests__/card-spec.tsx
> +        it('should support header', done => {
这里应该不需要 done，cy 是自带等待的。

2024-06-20 06:53 UTC, eternalsky commented on components/upload/__tests__/card-spec.tsx
> +            const onChange = cy.spy().as('onChangeSpy');
done 这里同上，后续不再赘述，所有的 done 都可以移除

2024-06-20 06:53 UTC, eternalsky commented on components/upload/__tests__/card-spec.tsx
> +                    super();
缺少入参补上就可以了，这里是测试，不是 src

2024-06-20 06:53 UTC, eternalsky commented on components/upload/__tests__/file-list-spec.tsx
>  import sinon from 'sinon';
这里没必要引用 sinon，cypress 已经内置了，用 cy 自己的即可。

2024-06-20 06:53 UTC, eternalsky commented on components/upload/__tests__/file-list-spec.tsx
>          xhr = sinon.useFakeXMLHttpRequest();
另外这个 beforeEach 和  afterEach 换成 cy 之后还有意义吗？

2024-06-20 06:53 UTC, eternalsky commented on components/upload/__tests__/index-spec.tsx
> +function triggerUploadEvent(cy: any, done: any, callback?: (wrapper: Wrapper) => void) {
done 和 cy 都是有明确的类型的，不应该是 any

2024-06-20 06:53 UTC, eternalsky commented on components/upload/__tests__/index-spec.tsx
> +function triggerUploadEvent(cy: any, done: any, callback?: (wrapper: Wrapper) => void) {
而且 cy 是全局的，不需要作为参数传递

2024-06-20 06:53 UTC, eternalsky commented on components/upload/__tests__/index-spec.tsx
> +function triggerUploadEvent(cy: any, done: any, callback?: (wrapper: Wrapper) => void) {
done 其实也是没有意义的，可以全部移除，理由同上。

2024-06-20 06:53 UTC, eternalsky commented on components/upload/__tests__/request-spec.ts
>  import assert from 'power-assert';
assert  和 sinon 都是 cy 里有的，不需要单独引用。

2024-06-20 06:53 UTC, eternalsky commented on components/upload/__tests__/text-spec.tsx
> +import sinon from 'sinon';
同上

2024-06-20 06:53 UTC, eternalsky commented on components/upload/__tests__/text-spec.tsx
> +        xhr = sinon.useFakeXMLHttpRequest();
同上

2024-06-20 06:53 UTC, eternalsky commented on components/upload/__tests__/util-spec.ts
>  import assert from 'power-assert';
同上

2024-06-20 06:53 UTC, eternalsky commented on components/upload/__tests__/util-spec.ts
> +        assert(fileToObject(file as unknown as UploadFile).uid === file.uid);
不用出现 as unknown，所有的 as unknown 强制类型转换背后必然都是类型不正确导致，这样只是忽略问题并不是解决问题。其他地方同

2024-06-20 06:53 UTC, eternalsky commented on components/upload/__tests__/util-spec.ts
>          assert(removeFileItem(file, files).length === files.length - 1);
tc 里不要出现 ts-expect-error，如果有问题就改成更正确的就好了。

2024-06-20 06:53 UTC, eternalsky commented on components/upload/card.tsx
> +         *file - 文件对象 - file object
放在 propTypes 里的注释都可以删除了，这些都已经转移到 types 里了。

2024-06-20 06:53 UTC, eternalsky commented on components/upload/card.tsx
> +        this.props.onProgress?.(value, targetItem);
这样就有点改变含义了，这里用 ! 来做判空即可。

2024-06-20 06:53 UTC, eternalsky commented on components/upload/card.tsx
> +        this.props.onProgress?.(value, targetItem);
下方相同，所有需要判空的地方用 ！

2024-06-20 06:53 UTC, eternalsky commented on components/upload/card.tsx
> +        const isExceedLimit = (this.state.value as Array<UploadFile>).length >= limit;
state.value 在什么情况下可能是 ObjectFile？目前看 value 只能是数组，那为什么 state.value 为什么可以单个

2024-06-20 06:53 UTC, eternalsky commented on components/upload/card.tsx
> +        const children = this.props.children || (locale?.card as ComponentLocaleObject)?.addPhoto;
这个应该是因为 types 里没有具体指定 upload 的 locale，可以参考一下其他组件里 locale 是如何具体指定的。

2024-06-20 06:53 UTC, eternalsky commented on components/upload/card.tsx
> +        // @ts-expect-error List.propTypes 类型不兼容
这里只是因为有可能为空，用 ！去空就可以了。

2024-06-20 06:53 UTC, eternalsky commented on components/upload/card.tsx
> +                    [className as string]: !!className,
去空用 ！

2024-06-20 06:53 UTC, eternalsky commented on components/upload/card.tsx
> +                className={className as string}
同上

2024-06-20 06:53 UTC, eternalsky commented on components/upload/card.tsx
> +                locale={locale as UploadLocale & ComponentLocaleObject}
同上

2024-06-20 06:53 UTC, eternalsky commented on components/upload/card.tsx
> +                value={this.state.value as Array<UploadFile>}
同上

2024-06-20 06:53 UTC, eternalsky commented on components/upload/card.tsx
> +                    value={this.state.value as UploadFile[]}
同上

2024-06-20 06:53 UTC, eternalsky commented on components/upload/card.tsx
> +                    ref={(ref: InstanceType<typeof Upload>) => this.saveRef(ref)}
这里不需要指定，是 saveRef 的类型里没有考虑到 null 的情况。

2024-06-24 07:38 UTC, FairyYang commented on components/upload/__docs__/demo/maxsize/index.tsx
> +            img.src = reader.result as string;
这里不是判空，result的类型如下： FileReader.result: string | ArrayBuffer | null

2024-06-24 08:16 UTC, FairyYang commented
重新提交了一版

2024-06-24 08:17 UTC, FairyYang commented
重新打开PR

2024-06-25 01:48 UTC, FairyYang commented on components/upload/card.tsx
> +                locale={locale as UploadLocale & ComponentLocaleObject}
这里不是判空

2024-06-25 01:48 UTC, FairyYang commented on components/upload/card.tsx
> +                value={this.state.value as Array<UploadFile>}
这里不是判空

2024-06-25 01:48 UTC, FairyYang commented on components/upload/card.tsx
> +                    value={this.state.value as UploadFile[]}
这里不是判空

2024-06-26 10:14 UTC, eternalsky requested changes

2024-06-26 10:14 UTC, eternalsky commented on components/upload/__tests__/util-spec.ts
> +        const file = { uid: 1, 1: 1 } as unknown as OriginalFile;
这里还是有很多 as unknown，理论上 as known 应该都不存在

2024-06-26 10:14 UTC, eternalsky commented on components/upload/card.tsx
> +        // @ts-expect-error limit可能为undefined
这里用判空就可以了。

2024-06-26 10:14 UTC, eternalsky commented on components/upload/card.tsx
> +                value={this.state.value as UploadFile[]}
state.value 本身不就是 UploadFile[] 吗，这里为什么还需要 as

2024-06-26 10:14 UTC, eternalsky commented on components/upload/dragger.tsx
> +    saveUploaderRef = (ref: InstanceType<typeof Upload>) => {
这里没有 null

2024-06-26 10:14 UTC, eternalsky commented on components/upload/dragger.tsx
> +            typeof (ref as unknown as { getInstance: () => InstanceType<typeof Upload> })
不要出现 as unknown

2024-06-26 10:14 UTC, eternalsky commented on components/upload/index.tsx
> +Upload.Card = ConfigProvider.config(Card, { componentName: 'Upload' }) as unknown as typeof Card;
加入子组件，可以使用公共的 assignSubComponent 方法，可以参考一下其他组件。

2024-06-26 10:14 UTC, eternalsky commented on components/upload/runtime/html5-uploader.tsx
> +        this.uploader = new Uploader(options as unknown as UploadOptions);
不要出现 as unknown

2024-06-26 10:14 UTC, eternalsky commented on components/upload/runtime/html5-uploader.tsx
> +                this.uploader.setOptions(options as unknown as UploadOptions);
同上

2024-06-26 10:14 UTC, eternalsky commented on components/upload/runtime/request.tsx
> +        formData.append(option.filename!, option.file as unknown as Blob);
同上

2024-06-26 10:14 UTC, eternalsky commented on components/upload/runtime/request.tsx
> +        option.onError!(e as unknown as UploadError);
同上

2024-06-26 10:14 UTC, eternalsky commented on components/upload/util.ts
> +    reader.readAsDataURL(file as unknown as Blob);
同上

2024-06-27 10:18 UTC, FairyYang commented
提交了一个commit，修复了上面的问题

2024-07-01 09:45 UTC, eternalsky requested changes

2024-07-01 09:45 UTC, eternalsky commented on components/upload/__tests__/util-spec.ts
> +        const files = [{ uid: 3 }, { uid: 2 }];
这里为什么要把数据删除一部分呢

2024-07-01 09:45 UTC, eternalsky commented on components/upload/card.tsx
> +                value={this.state.value as UploadFile[]}
这个还没有改

2024-07-01 09:50 UTC, eternalsky requested changes

2024-07-01 09:50 UTC, eternalsky commented on components/upload/list.tsx
> +        const size = this.sizeCaculator(file.size as unknown as string);
这里还有 as unknown

2024-07-01 09:50 UTC, eternalsky commented on components/upload/list.tsx
> +        fileSize = fileSize.toFixed(2) as unknown as number;
同上

2024-07-01 09:50 UTC, eternalsky commented on components/upload/upload.tsx
> +                        value={this.state.value as UploadFile[]}
这里也有类似问题

2024-07-01 09:50 UTC, eternalsky commented on components/upload/upload.tsx
> +                    // @ts-expect-error 此处的Ref类型不正确，不知道如何处理，需要评审一下
这个线下对清楚

2024-07-01 09:55 UTC, eternalsky requested changes

2024-07-01 09:55 UTC, eternalsky commented on components/upload/upload.tsx
> +        // @ts-expect-error this.uploaderRef.startUpload 继承自Base，Base中的startUpload没有入参，所以这里调用会有TS问题
没有入参加上入参不就可以了~ 参考一下其他有 Base 的组件

2024-07-01 09:55 UTC, eternalsky commented on components/upload/upload.tsx
>                      <div tabIndex="0" role="button" className={`${prefix}upload-text`}>
tabIndex  这个改动比较小，可以直接改掉

2024-07-02 09:26 UTC, FairyYang commented on components/upload/list.tsx
> +        const size = this.sizeCaculator(file.size as unknown as string);
![Uploading image.png…]()

2024-07-02 09:27 UTC, FairyYang commented on components/upload/list.tsx
> +        const size = this.sizeCaculator(file.size as unknown as string);
![Uploading 65E72D94-74D9-4350-8080-53586AF7902C.png…]()

2024-07-02 09:28 UTC, FairyYang commented on components/upload/list.tsx
> +        const size = this.sizeCaculator(file.size as unknown as string);
![65E72D94-74D9-4350-8080-53586AF7902C](https://github.com/alibaba-fusion/next/assets/21052604/081efb15-5db0-41a2-9a6b-0015c0a1bfcc)

2024-07-02 09:32 UTC, FairyYang commented on components/upload/list.tsx
> +        fileSize = fileSize.toFixed(2) as unknown as number;
![image](https://github.com/alibaba-fusion/next/assets/21052604/1277e27d-e99e-417d-8826-cdede3bfafea)

2024-07-04 01:41 UTC, eternalsky commented on components/upload/util.ts
> +) {
这里感觉用泛型把类型收的太窄了。从实现上来看，这个 remove 逻辑，并不要求 fileList 的 item 必须要和 file 同型，只是过滤 uid 或者 name 相等的情况。即使其他字段不相同，也是可以过滤的。而这里加了泛型之后，就要求两者类型必须完全一致了。这也是为什么下面测试里还得额外指定类型的原因了。

2024-07-04 01:41 UTC, eternalsky commented on components/upload/__tests__/util-spec.ts
> +        const files: { uid: number; [key: number]: number }[] = [
这里没必要指定类型，removeFileItem 那里已经做出了说明。

2024-07-04 01:41 UTC, eternalsky commented on components/upload/list.tsx
> +        const size = this.sizeCaculator(file.size as unknown as string);
那这里应该用 expect-error 并说明原因，不要出现 as unknown。

2024-07-04 01:41 UTC, eternalsky commented on components/upload/list.tsx
> +        fileSize = fileSize.toFixed(2) as unknown as number;
同上

2024-07-04 02:27 UTC, eternalsky approved these changes

2024-07-04 02:28 UTC, merged