fix(Select): should be able to select multiple options in multi-select, close #3590
alibaba-fusion/next pull request #4845
Opened 2024-05-15 02:20 UTC by FairyYang

fix(Select): should be able to select multiple options in multi-select, close #3590

2024-06-14 17:23 UTC, FairyYang commented
我收到了

2024-06-20 11:50 UTC, eternalsky requested changes

2024-06-20 11:50 UTC, eternalsky commented on components/select/select.tsx
> +            mode !== 'multiple'
这个不应该是改变默认行为，而是新增一个配置项，允许在多选时不清空 search

2024-06-20 11:53 UTC, eternalsky commented on components/select/select.tsx
> +            mode !== 'multiple'
可以仿照 antd select 增加一个 autoClearSearchValue 的配置项，默认为 true

2024-06-27 12:28 UTC, eternalsky requested changes

2024-06-27 12:28 UTC, eternalsky commented on components/select/types.ts
> +     * @defaultValue true
这个默认值应该是 false

2024-06-27 12:28 UTC, eternalsky commented on components/select/__tests__/index-spec.tsx
> -        const handleSearchClear = cy.spy().as('onSearchClear');
原有的测试行为不应该被改变，新增的属性默认应该是 false

2024-06-28 06:32 UTC, FairyYang commented on components/select/__tests__/index-spec.tsx
> -        const handleSearchClear = cy.spy().as('onSearchClear');
autoClearSearchValue默认为false的话，需要修改原有的测试用例，因为对于原有的组件，是默认会清空搜索。

2024-06-28 06:45 UTC, FairyYang commented
1、提交了新的commit，测试行为的修改去掉了。
2、autoClearSearchValue默认为false的话，需要修改原有的测试用例，因为原有的组件行为，默认会清空搜索。所以autoClearSearchValue默认为true比较合理。

2024-07-01 07:43 UTC, eternalsky commented on components/select/__tests__/index-spec.tsx
> -        const handleSearchClear = cy.spy().as('onSearchClear');
既然这里以前的默认行为是 true 的话，为什么这里要修改测试用例呢

2024-07-01 07:48 UTC, eternalsky approved these changes

2024-07-01 07:48 UTC, merged