fix(Select): should support select all multiple on search mode and concat data, close #4810
alibaba-fusion/next pull request #4850
Opened 2024-05-16 03:36 UTC by FairyYang

2024-05-16 12:11 UTC, eternalsky requested changes

2024-05-16 12:11 UTC, eternalsky commented on components/select/__tests__/index-spec.tsx
> +    it.only('should support select all mutiple on search mode and concat data', () => {
这里还留着 only

2024-05-16 12:20 UTC, eternalsky commented
check changed 的问题，我在 master 上已经修复，重新 rebase 一下应该就可以了

2024-05-16 12:32 UTC, eternalsky commented on components/select/select.tsx
> +                ...((this.state.value as ObjectItem['value'][]) || []),
这里强制 as 有些问题，state.value 也有可能不是 ObjectItem['value'][]，他的类型是 DataSourceItem | DataSourceItem[] 就算是全选只会出现在多选场景，不可能是 DataSourceItem，但也有可能是 ObectItem[]，tc 中应该补充 defaultValue 是 useDetailValue 的情况

2024-05-17 06:15 UTC, FairyYang commented
重新提交了代码，其中有两个commit

2024-05-17 10:47 UTC, eternalsky requested changes

2024-05-17 10:47 UTC, eternalsky commented on components/select/__tests__/index-spec.tsx
> +        cy.mount(
这第二个 case 是在测试什么，好像没经过 selectAll 啊

2024-05-17 10:47 UTC, eternalsky commented on components/select/select.tsx
> +                ...((this.state.value as (ObjectItem['value'] | ObjectItem)[]) || []),
这里你没懂我的意思，我的意思不是说这里类型不全要加个类型。而是这里强行指定是 ObjectItem['value'] 逻辑上错误，没有覆盖 detailedValue 的场景

2024-05-20 06:15 UTC, FairyYang commented on components/select/select.tsx
> +                ...((this.state.value as (ObjectItem['value'] | ObjectItem)[]) || []),
我理解 detailedValue场景下，value 的类型是ObjectItem[]

2024-05-20 06:27 UTC, FairyYang commented on components/select/__tests__/index-spec.tsx
> +        cy.mount(
测试的是useDetailValue时，全选的效果， 修改了一下，已经提交了

2024-05-30 01:57 UTC, eternalsky approved these changes

2024-05-30 01:57 UTC, merged