fix(DatePicker2): Unable to enter space to enter time
alibaba-fusion/next pull request #4853
Opened 2024-05-21 09:10 UTC by luolin-ck

close #4790

2024-06-20 12:13 UTC, eternalsky requested changes

2024-06-20 12:13 UTC, eternalsky commented on components/date-picker2/__tests__/index-spec.js
> +            changeInput('2020-11-11 09:23:23');
感觉这个测试用例无法覆盖相应的变化，simulate change 是模拟的 change 事件，并不是一个一个字符输入进去的，因此无法模拟中间输入空格的情况，相当于把 2020-11-11 09:23:23 一下子输入进去。这个原本就是支持的。写测试用例还是应该遵循，首先用测试用例能复现 issue，然后再通过修改 src 来修复 issue。

2024-06-20 12:13 UTC, eternalsky commented on components/date-picker2/picker.jsx
> +                    triggerClickKeycode={[]}
为啥这里加入一个空数组就可以解这个问题了呢

2024-06-21 02:25 UTC, luolin-ck commented on components/date-picker2/picker.jsx
> +                    triggerClickKeycode={[]}
这个是因为popup组件，存在默认值，默认阻止空格和回车键事件。因此增加了triggerClickKeycode的属性
<img width="725" alt="image" src="https://github.com/alibaba-fusion/next/assets/92377270/654440f8-f59f-4f8c-a2c0-d54f3650c141">

2024-06-28 01:40 UTC, eternalsky requested changes

2024-07-01 07:35 UTC, eternalsky approved these changes

2024-07-01 07:38 UTC, merged