refactor(Overlay): ts & docs & test tools
alibaba-fusion/next pull request #4855
Opened 2024-05-24 02:51 UTC by eamonzym

refactor(Overlay): ts & docs & test tools

2024-06-12 01:25 UTC, eternalsky requested changes

2024-06-12 01:25 UTC, eternalsky commented on components/overlay/types.ts
> +     * @en Container of the overlay, if it is a function, it should return ref, if it is a string, it is should be the id of the DOM element, it can also be passed the DOM element directly.
这里写了两遍

2024-06-12 01:25 UTC, eternalsky commented on components/overlay/utils/find-node.ts
> +    let realTarget: typeof target | Element | Node | Text | void = target;
Element | Node | Text 不就在 typeof target 里面吗

2024-06-20 02:35 UTC, eternalsky requested changes

2024-06-20 02:35 UTC, eternalsky commented on components/overlay/popup-v2.tsx
> +                cloneElement(overlayNode as ReactElement, {
另外从下面的逻辑来看，overlayNode 貌似是支撑不起来 ReactNode 这个 type 的，那为什么外面的定义里跟实际是不匹配的呢~

2024-06-20 02:35 UTC, eternalsky commented on components/overlay/overlay.tsx
> +    overlay: Overlay | null;
这里最好也是用 InstanceType

2024-06-20 02:35 UTC, eternalsky commented on components/overlay/utils/find-node.ts
> +/* eslint-disable @typescript-eslint/no-unnecessary-type-constraint */
这个注释也可以删除了吧？

2024-06-20 02:40 UTC, eternalsky requested changes

2024-06-20 02:40 UTC, eternalsky commented on components/select/types.ts
> +const { Popup } = Overlay;
这里的改造没太看懂，和之前有什么区别吗

2024-06-21 01:39 UTC, eternalsky requested changes

2024-06-21 01:39 UTC, eternalsky commented on components/overlay/types.ts
> +    /**
Overlay v1 和 v2 是根据一个 props 进行切换的，最终还是统一在一个 OverlayProps，只是有些是 v1 或者 v2 专属，我的意思是这里对外还是 OverlayProps，但是对内到具体组件，可以是分开的，通过 Pick 或者 Omit，以及一些覆盖逻辑，让组件内部类型更加准确。

2024-06-21 01:43 UTC, eternalsky requested changes

2024-06-21 01:43 UTC, eternalsky commented on components/overlay/types.ts
> +    v2?: boolean;
v2 的值既然区分 v1/v2 了，那这里就不再是boolean 了，而是具体的 true/false ，详细可以参考 dialog

2024-06-26 07:07 UTC, eternalsky requested changes

2024-06-26 07:07 UTC, eternalsky commented on components/overlay/__docs__/demo/baisc/index.tsx
> +class Demo extends Component<OverlayProps, { visible: boolean }> {
这个 props 不太对吧，没看到这个组件接收这个 props，其实这里不用指定泛型，去掉 constructor，把 state 提出来就可以了。

2024-06-26 07:07 UTC, eternalsky commented on components/overlay/__docs__/demo/baisc/index.tsx
> +class Demo extends Component<OverlayProps, { visible: boolean }> {
其他 demo 也有类似的问题，可以统一改一下，可以参考一下比如 dialog 组件。

2024-06-26 07:07 UTC, eternalsky commented on components/menu/view/create.tsx
> +            align: align as string,
这里的 align 为什么需要 as string？

2024-06-26 07:07 UTC, eternalsky commented on components/message/toast.tsx
> +                align={align as string}
同上

2024-06-26 07:07 UTC, eternalsky commented on components/drawer/types.ts
> +type HTMLAttributesWeak = PopupProps;
这样改完之后感觉就没有留着这个的必要了。

2024-06-26 07:07 UTC, eternalsky commented on components/dialog/dialog.tsx
> +            align: (useCSS ? false : align) as string,
这里的 align 为什么需要 as string？

2024-06-26 07:18 UTC, eternalsky requested changes

2024-06-26 07:18 UTC, eternalsky commented on components/overlay/types.ts
> +    needAdjust?: boolean;
这个属性在 v2 是 deprecated 的，这里应该标记 @deprecated。并且在文档中 skip

2024-07-02 06:16 UTC, eamonzym commented on components/menu/view/create.tsx
> +            align: align as string,
overlay的align在v1是boolean｜string，v2是string。目前使用as string对类型收窄，后面可做类型守卫优化掉

2024-07-02 06:16 UTC, eamonzym commented on components/dialog/dialog.tsx
> +            align: (useCSS ? false : align) as string,
overlay的align在v1是boolean｜string，v2是string。目前使用as string对类型收窄，后面可做类型守卫优化掉

2024-07-03 01:34 UTC, eamonzym commented on components/overlay/popup-v2.tsx
> +    let overlayNode = overlay ? (overlay as ReactElement) : (children as ReactElement);
overlay的类型调整成了ReactElement；children需要为ReactNode，其他组件传入的属性类型是ReactNode（比如：Drawer组件的content类型是ReactNode）所以得在这里做了as ReactElement

2024-07-03 12:59 UTC, eternalsky commented on components/dialog/dialog.tsx
> +            align: (useCSS ? false : align) as string,
但这个是 dialog 啊，dialog 传给 overlay 应该就没有类型收窄的点了啊

2024-07-19 02:14 UTC, eternalsky requested changes

2024-07-19 02:14 UTC, eternalsky commented on components/overlay/__tests__/index-spec.tsx
> +            downloadRef: InstanceType<typeof Button> | HTMLElement | null;
这里的类型还是不对，downloadRef 怎么会是 HTMLElement 呢？

2024-07-19 02:14 UTC, eternalsky commented on components/overlay/__tests__/index-spec.tsx
> +                            popupContainer={() => this.downloadRef as HTMLElement}
这里拿到的就是 ReactInstance，不需要 as 成 HTMLElement

2024-07-24 06:54 UTC, eternalsky requested changes

2024-07-24 06:54 UTC, eternalsky commented on components/balloon/index.d.ts
> +    popupContainer?: Target;
这里直接复用 Target 感觉不好，应该用 PopupProps 里的属性。

2024-07-25 02:05 UTC, eternalsky approved these changes
LGTM

2024-07-25 02:09 UTC, merged