feat(Tree): support scrollIntoView, close #2930
alibaba-fusion/next pull request #4860
Opened 2024-06-12 03:05 UTC by wangw11056

Add a new property to the Tree component to support the scrollIntoView when using the filterTreeNode property.

2024-06-12 03:12 UTC, wangw11056 commented
close #2930

2024-06-12 06:31 UTC, wangw11056 commented
close #2930

2024-06-12 06:31 UTC, wangw11056 commented
close #2930

2024-06-21 03:23 UTC, eternalsky requested changes

2024-06-25 11:34 UTC, wangw11056 commented on components/tree/types.ts
> +    scrollIntoView?: boolean;
加@Skip是因为我不确定该属性会在哪个版本上线，理论上我理解应该加上@version，但是我移除并调整为@Skip

2024-06-27 12:25 UTC, eternalsky commented on components/tree/types.ts
> +    scrollIntoView?: boolean;
> 加@Skip是因为我不确定该属性会在哪个版本上线，理论上我理解应该加上@Version，但是我移除并调整为@Skip

version 理论上应该是现在版本号+ 一个最后位

2024-07-03 03:48 UTC, eternalsky requested changes

2024-07-03 03:48 UTC, eternalsky commented on components/tree/__docs__/demo/search-tree/index.tsx
> +                this.refs.treeRef?.getInstance?.().scrollFilterNodeIntoView();
ts 有报错

2024-07-03 03:48 UTC, eternalsky commented on components/tree/__docs__/demo/search-tree/index.tsx
> +                    ref="treeRef"
ref 为字符串的用法已经 deprecated 了，不能继续使用。这也是为啥上面 ts 会报错的原因。

2024-07-03 03:48 UTC, eternalsky commented on components/tree/__tests__/index-spec.tsx
> +            // eslint-disable-next-line cypress/no-unnecessary-waiting
正常情况下，不需要 wait，cy.get  自己就是带延时重试的能力的。

2024-07-03 03:48 UTC, eternalsky commented on components/tree/__tests__/index-spec.tsx
> +                isInViewport('.k-100-100-100-100').should('be.true');
这个写法也蛮奇怪的，should 部分为什么不能放到 isInViewPort 里。

2024-07-03 03:48 UTC, eternalsky commented on components/tree/__tests__/index-spec.tsx
> +                isInViewport('.k-0-0').should('be.true');
同上

2024-07-03 03:48 UTC, eternalsky commented on components/tree/view/tree.tsx
> +            return c;
这里为什么还要 return c？

2024-07-03 03:48 UTC, eternalsky commented on components/tree/view/tree.tsx
> +            itemNode.scrollIntoView?.(arg);
应该先尝试 scrollIntoViewIfNeed ，没有的情况再用 scrollIntoView

2024-07-03 03:48 UTC, eternalsky commented on components/tree/view/tree.tsx
> +            // I don't care...
这里 i dont care，感觉也不是很好。最好还是 console warn 出来会好一些。

2024-07-03 03:48 UTC, eternalsky commented on components/tree/__tests__/index-spec.tsx
> +            .then(async () => {
这里为什么要 async，没看到 await 的地方

2024-07-03 03:48 UTC, eternalsky commented on components/tree/__tests__/index-spec.tsx
> +        return Cypress.$(targetSelector)[targetIndex].getBoundingClientRect();
这里为什么不用 cy.get 之后从 then 里拿呢？

2024-07-03 03:48 UTC, eternalsky commented on components/tree/__tests__/index-spec.tsx
> +        return Cypress.$(targetSelector)[targetIndex].getBoundingClientRect();
加上这个之后和其他 cy 指令混排，导致指令的顺序上就不太对了。

2024-07-03 12:47 UTC, eternalsky requested changes

2024-07-03 12:47 UTC, eternalsky commented on components/tree/__tests__/index-spec.tsx
> +            cy.then(() => {
这个 cy.then 不用放在另一个 cy.then 里面

2024-07-03 12:47 UTC, eternalsky commented on components/tree/__tests__/index-spec.tsx
> +            cy.then(() => {
同上

2024-07-04 02:08 UTC, eternalsky approved these changes

2024-07-04 12:28 UTC, merged