refactor(Form): convert to TypeScript, impove docs and tests, close#4585
alibaba-fusion/next pull request #4862
Opened 2024-06-17 09:45 UTC by FairyYang

2024-08-08 09:49 UTC, eternalsky requested changes

2024-08-08 09:49 UTC, eternalsky commented on components/form/__tests__/index-spec.tsx
> +            const Tag = (props: { children: React.ReactNode }) => {
应从 React 中解构

2024-08-08 09:49 UTC, eternalsky commented on components/form/__tests__/index-spec.tsx
> +            const Tag = (props: { children: React.ReactNode }) => {
同上

2024-08-08 09:49 UTC, eternalsky commented on components/form/__tests__/index-spec.tsx
> +            cy.get('.next-form-item:first-of-type').should('have.class', 'has-success');
感觉用 eq(0) 更通用一些

2024-08-08 09:49 UTC, eternalsky commented on components/form/__tests__/validate-spec.tsx
> +            expect(v.first).to.equal('test');
这个 expect 能执行到吗，感觉还没执行到，测试用例就结束了。

2024-08-08 09:49 UTC, eternalsky commented on components/form/__tests__/validate-spec.tsx
> +            expect(v.first).to.equal('test');
这里还是应该用 spy 来搞

2024-08-08 09:49 UTC, eternalsky commented on components/form/__tests__/validate-spec.tsx
> +            expect(v.first).to.equal('test');
同上

2024-08-08 09:49 UTC, eternalsky commented on components/form/__tests__/validate-spec.tsx
> +            expect(v.first).to.equal('test');
同上

2024-08-08 09:49 UTC, eternalsky commented on components/form/__tests__/validate-spec.tsx
> +            expect(v.first).to.equal('test');
同上，其他不再赘述，统一看一下

2024-08-08 09:49 UTC, eternalsky commented on components/form/__tests__/validate-spec.tsx
> +        class Demo extends React.Component<DemoProps> {
同上

2024-08-08 09:49 UTC, eternalsky commented on components/form/__tests__/validate-spec.tsx
> +        cy.get('input#first').then($input => {
这个感觉用 should(have.value, xxx) 更好，这样写有点麻烦

2024-08-08 09:49 UTC, eternalsky commented on components/form/__tests__/validate-spec.tsx
> +            const inputValue = $input.prop('value');
同上，类似的问题可以统一看一下，后面不再赘述

2024-08-09 07:44 UTC, eternalsky requested changes

2024-08-09 07:44 UTC, eternalsky commented on components/form/form.tsx
> +function pickerDefined(obj: Record<string, unknown>) {
这个返回值体现不出函数的逻辑，可以更准确一些方便后面使用。
```ts
type RemoveUndefined<T extends Record<string, any>> = {
  [K in keyof T as T[K] extends undefined ? never : K]: T[K];
};
```

2024-08-09 07:44 UTC, eternalsky commented on components/form/form.tsx
> +function preventDefault(e: FormEvent<HTMLFormElement>) {
这里也是类型写窄了

2024-08-09 07:44 UTC, eternalsky commented on components/form/form.tsx
> +            const options: {
感觉这里不需要额外定义类型，是可以推导的。

2024-08-09 07:44 UTC, eternalsky commented on components/form/form.tsx
> +                // @ts-expect-error messages 的类型是 MessagesConfig,props.locale.Validate 类型是 string，所以这里会报错
这是因为 locale 在 types 里没有指定正确导致的，参考其他组件。

2024-08-09 07:44 UTC, eternalsky commented on components/form/form.tsx
> +            props.saveField?.(this._formField);
判空用 !

2024-08-09 07:44 UTC, eternalsky commented on components/form/form.tsx
> +        this.props.onChange?.(this._formField?.getValues(), {
同上，? 相当于是修改了逻辑，这里判空用 !

2024-08-09 07:44 UTC, eternalsky commented on components/form/form.tsx
> +            // @ts-expect-error JSX 元素类型“Tag”不具有任何构造签名或调用签名。
这里感觉不是 expect-error

2024-08-09 07:44 UTC, eternalsky commented on components/form/form.tsx
> +                role="form"
role 为什么从 grid 变成 form 呢

2024-08-09 07:44 UTC, eternalsky commented on components/form/index.tsx
> +    transform: /* istanbul ignore next */ (props, deprecated) => {
无用注释可以去掉

2024-08-09 07:44 UTC, eternalsky commented on components/form/index.tsx
> +        transform: /* istanbul ignore next */ (props, deprecated) => {
无用注释可以去掉

2024-08-09 07:44 UTC, eternalsky commented on components/form/item.tsx
> +                : this.context._formLabelForErrorMessage;
context 在 react 中默认是 any，这里应该将 context 定义清楚

2024-08-09 07:44 UTC, eternalsky commented on components/form/item.tsx
> +                    type?: { _typeMark: 'form_item' | 'form_error'; displayName: string };
这里为什么不用 ChildExtraProperties 了呢

2024-08-09 07:44 UTC, eternalsky commented on components/form/item.tsx
> +        labelAlign: 'top' | 'left' | 'inset' | undefined,
这里应该直接引用  props.labelAlign 的类型

2024-08-09 07:44 UTC, eternalsky commented on components/form/item.tsx
> +        device: 'desktop' | 'phone' | 'tablet' | undefined
同上

2024-08-09 07:44 UTC, eternalsky commented on components/form/reset.tsx
> +        onClick?.();
同上

2024-08-09 07:44 UTC, eternalsky commented on components/form/submit.tsx
> +            onClick?.();
同上

2024-08-09 07:44 UTC, eternalsky commented on components/form/submit.tsx
> +                onClick?.(field.getValues(), errors, field);
同上

2024-08-09 07:44 UTC, eternalsky commented on components/form/submit.tsx
> +                onClick?.(field.getValues(), errors, field);
同上

2024-08-09 07:44 UTC, eternalsky commented on components/form/submit.tsx
> +            onClick?.(field.getValues(), null, field);
同上

2024-08-09 07:44 UTC, eternalsky commented on components/form/types.ts
> +import NextField, { type FieldValues } from '../field';
看一下这个 check 问题

2024-08-09 07:44 UTC, eternalsky commented on components/form/types.ts
> +    [propName: string]: unknown;
这里需要一个通用检索吗

2024-08-09 07:44 UTC, eternalsky commented on components/form/types.ts
> +    prefix?: string;
这个 commonProps 里已经有了

2024-08-09 07:44 UTC, eternalsky commented on components/form/types.ts
> +    fieldOptions?: object;
这里是 object 明显不太准确吧~

2024-08-09 07:44 UTC, eternalsky commented on components/form/types.ts
> +    style?: object;
同上

2024-08-09 07:44 UTC, eternalsky commented on components/form/types.ts
> +    direction?: 'hoz';
只有一个值？

2024-08-09 07:44 UTC, eternalsky commented on components/form/types.ts
> +    field?: unknown;
这个应该不是 unknown 吧

2024-08-09 07:44 UTC, eternalsky commented on components/form/types.ts
> +    children?: React.ReactNode | (() => void);
联合的后半段是干什么的

2024-08-09 07:44 UTC, eternalsky commented on components/form/types.ts
> +    field?: unknown;
这个应该不是 unknown 吧

2024-08-09 07:44 UTC, eternalsky commented on components/form/types.ts
> +    field?: unknown;
这个应该不是 unknown 吧

2024-08-09 07:44 UTC, eternalsky commented on components/form/types.ts
> +    validate?: boolean | Array<unknown>;
这个应该不是 unknown 吧

2024-08-09 07:44 UTC, eternalsky commented on components/form/types.ts
> +    renderPreview?: (values: unknown, props: unknown) => unknown;
这个应该不是 unknown 吧

2024-08-09 07:44 UTC, eternalsky commented on components/form/types.ts
> +    formatTrigger?: string | Array<unknown>;
这个应该不是 unknown 吧

2024-08-09 07:44 UTC, eternalsky commented on components/form/types.ts
> +    validator?: (rule: unknown, value: unknown, callback: unknown) => void;
这个应该不是 unknown 吧

2024-08-09 07:44 UTC, eternalsky commented on components/form/types.ts
> +    lengthTrigger?: string | Array<unknown>;
这个应该不是 unknown 吧

2024-08-09 07:44 UTC, eternalsky commented on components/form/types.ts
> +    minmaxLengthTrigger?: string | Array<unknown>;
这个应该不是 unknown 吧

2024-08-09 07:44 UTC, eternalsky commented on components/form/types.ts
> +    minmaxTrigger?: string | Array<unknown>;
这个应该不是 unknown 吧

2024-08-09 07:44 UTC, eternalsky commented on components/form/types.ts
> +    requiredTrigger?: string | Array<unknown>;
这个应该不是 unknown 吧

2024-08-20 03:40 UTC, FairyYang commented on components/form/__docs__/demo/responsive-grid/index.tsx
> +    } = {
这里的state的labelAlign、device的值是会变化的，as const不适合

2024-08-21 10:01 UTC, FairyYang commented on components/form/__tests__/index-spec.tsx
> +            cy.mount(
因为旧版本用例根据props来判断，cypress不适合对props操作，根据用例的描述，是想测试下form渲染，所以改成了现在的版本

2024-08-21 10:05 UTC, FairyYang commented on components/form/__tests__/index-spec.tsx
> +                    <FormItem label="test">
此处也是因为旧版本用例根据props来判断，cypress不适合对props操作，根据用例的描述和旧代码，推测是想测试下form direction属性的渲染，所以改成了现在的版本

2024-08-22 04:08 UTC, FairyYang commented on components/form/types.ts
> +import NextField, { type FieldValues } from '../field';
这个引用中 NextField  FieldValues都是作为type引入的。如果分开引用，可以都加type，但是又不符合TS一个路径只能有一条引用的规则

2024-08-22 04:11 UTC, FairyYang commented on components/form/types.ts
> +    direction?: 'hoz';
只有这些地方用到了direction，难道要改成string？ 
![Uploading image.png…]()

2024-08-22 04:11 UTC, FairyYang commented on components/form/types.ts
> +    direction?: 'hoz';
![image](https://github.com/user-attachments/assets/8c763812-f34c-463a-b6ca-d5a04d532504)

2024-08-22 04:14 UTC, FairyYang commented on components/form/types.ts
> +    children?: React.ReactNode | (() => void);
是根据注释和这些代码来推导的  
![image](https://github.com/user-attachments/assets/1e233f77-6e82-46fd-bd44-57e9259f917e)

2024-08-22 07:27 UTC, FairyYang commented on components/form/types.ts
> +    renderPreview?: (values: unknown, props: unknown) => unknown;
应该是unknown吧，根据包裹的组件的 value 类型而决定的

2024-08-22 07:30 UTC, FairyYang commented on components/form/types.ts
> +    lengthTrigger?: string | Array<unknown>;
这里推导不出来是什么类型，难道是 string[]?

2024-08-22 07:31 UTC, FairyYang commented on components/form/types.ts
> +    minmaxLengthTrigger?: string | Array<unknown>;
同上，先改为了string | Array<string>

2024-08-30 04:03 UTC, eternalsky commented on components/form/types.ts
> +    renderPreview?: (values: unknown, props: unknown) => unknown;
如果是这样的话，如何确定入参第一个是 values 第二个是 props 的呢~

2024-08-30 04:03 UTC, eternalsky commented on components/form/types.ts
> +    formatTrigger?: string | Array<unknown>;
这个没改

2024-08-30 04:08 UTC, eternalsky commented on components/form/types.ts
> +    minmaxLengthTrigger?: string | Array<unknown>;
核心问题还是 context 没有声明类型，现在还是 any，所以推不出来。

2024-08-30 04:08 UTC, eternalsky commented on components/form/types.ts
> +    minmaxTrigger?: string | Array<unknown>;
同上

2024-08-30 04:08 UTC, eternalsky commented on components/form/types.ts
> +    requiredTrigger?: string | Array<unknown>;
同上

2024-09-14 06:23 UTC, FairyYang commented on components/form/form.tsx
> +                role="form"
因为gride不符合a11y的语义，会报错

2024-09-14 07:08 UTC, FairyYang commented on components/form/types.ts
> +import NextField, { type FieldValues } from '../field';
![image](https://github.com/user-attachments/assets/a2e3075d-a900-4a63-bbea-9ac84971675b)
会有这个报错

2024-09-14 07:26 UTC, FairyYang commented on components/form/types.ts
> +    children?: React.ReactNode | (() => void);
![image](https://github.com/user-attachments/assets/f4ebeb8c-d50c-42f7-82b8-0f8d61b8742c)
已经改成了这样的

2024-09-14 07:28 UTC, FairyYang commented on components/form/types.ts
> +    renderPreview?: (values: unknown, props: unknown) => unknown;
这里不知道怎么修改了

2024-09-14 07:36 UTC, FairyYang commented on components/form/types.ts
> +    formatTrigger?: string | Array<unknown>;
![image](https://github.com/user-attachments/assets/89ad7f3b-23f5-4242-af88-b236b9190db7)
这个已经改过了

2024-09-14 08:29 UTC, FairyYang commented on components/form/form.tsx
> +            // @ts-expect-error JSX 元素类型“Tag”不具有任何构造签名或调用签名。ts(2604)
这里去掉会报错  
![image](https://github.com/user-attachments/assets/d869c57c-811a-4645-9c49-5a28132d0e70)

2024-09-14 08:54 UTC, FairyYang commented on components/form/enhance.tsx
> +    const result: {
![image](https://github.com/user-attachments/assets/84c86936-2d28-4366-81b5-ee9a4d0020ef)
在context定义类型后，这里感觉还是不需要修改

2024-09-18 02:42 UTC, eternalsky requested changes

2024-09-18 02:42 UTC, eternalsky commented on components/form/__tests__/index-spec.tsx
> +            cy.get('.next-form-item:first-of-type').eq(0).should('have.class', 'has-success');
有 eq(0) 就不需要 first-of-type 了吧

2024-09-18 02:42 UTC, eternalsky commented on components/form/form.tsx
> +            // @ts-expect-error JSX 元素类型“Tag”不具有任何构造签名或调用签名。ts(2604)
这是因为 Tag 可能是 undefined 的原因吧，但实际上 Tag 不可能是 undefined

2024-09-18 02:42 UTC, eternalsky commented on components/form/form.tsx
> +                role="form"
报什么错呢？

2024-09-18 02:42 UTC, eternalsky commented on components/form/submit.tsx
>           * 点击提交后触发
这里注释也可以删除了

2024-09-18 02:42 UTC, eternalsky commented on components/form/types.ts
> +import NextField, { type FieldValues } from '../field';
import * 之后就是全集了，而不是 default ，你这里应该是用的 default

2024-09-18 02:42 UTC, eternalsky commented on components/form/types.ts
> +import React, { type RefObject } from 'react';
这里的 check 问题看一下。

2024-09-18 02:42 UTC, eternalsky commented on components/form/types.ts
> +import React, { type RefObject } from 'react';
和下面的 NextField 类似

2024-09-18 02:42 UTC, eternalsky commented on components/form/types.ts
> +    formatTrigger?: string | Array<unknown>;
我是说 Array<unknown> 里这个 unknown

2024-09-18 02:42 UTC, eternalsky commented on components/form/types.ts
> +    style?: object;
这个属性删除了？

2024-09-18 02:42 UTC, eternalsky commented on components/form/types.ts
> +    children?: React.ReactNode | (() => void);
这个看起来也不太对，首先 state 可以是 undefined 没有体现，其次返回值不是 void

2024-09-18 02:42 UTC, eternalsky commented on components/form/types.ts
> +    renderPreview?: (values: unknown, props: unknown) => unknown;
这是 Demo 文件吧，并不是源代码，源代码里也是用到过的，你再仔细看看~

2024-09-18 02:42 UTC, eternalsky commented on components/form/types.ts
> +    formatTrigger?: string | Array<unknown>;
我是说 Array<unknown> 里的 unknown

2024-09-18 02:42 UTC, eternalsky commented on components/form/enhance.tsx
> +        message?: unknown;
这两个看起来类型是可知的，不是 unknown

2024-09-18 02:42 UTC, eternalsky commented on components/form/enhance.tsx
> +        message?: unknown;
Rule 的标准类型，其实 @alifd/field 是有定义的，可以直接引用，这里不必自己再定义一遍。

2024-09-18 07:15 UTC, FairyYang commented on components/form/form.tsx
> +                role="form"
![image](https://github.com/user-attachments/assets/b240da5c-8d1e-4655-8d2b-443139b2211a)

2024-09-18 07:18 UTC, FairyYang commented on components/form/types.ts
> +    style?: object;
加回来了

2024-09-18 07:28 UTC, FairyYang commented on components/form/types.ts
> +    renderPreview?: (values: unknown, props: unknown) => unknown;
![image](https://github.com/user-attachments/assets/10c47abe-2b19-4502-95a1-65e635dca302)
源代码里没有能推导renderPreview类型的依据

2024-09-19 06:47 UTC, eternalsky requested changes

2024-09-19 06:47 UTC, eternalsky commented on components/form/types.ts
> +import type { Field } from '..';
types 不能从 index 引用，这样就循环依赖了。

2024-09-19 06:47 UTC, eternalsky commented on components/form/types.ts
> +    renderPreview?: (values: unknown, props: unknown) => unknown;
对啊，那既然完全不可知，为什么上面的会认为有两个参数分别是 value 和 props 呢？

2024-09-19 06:47 UTC, eternalsky commented on components/form/form.tsx
> +            component: Tag = 'form',
这样修改其实就修改原有逻辑了，技术升级这次不动原有逻辑，其实这里应该是要重新声明一下 props，把有 default 值的都排除空，参考其他做过的组件加上 withDefault

2024-09-19 06:47 UTC, eternalsky commented on components/form/__tests__/validate-spec.tsx
> +        cy.get('.next-form-item-help:first-of-type').should('have.text', 'first 是必填字段');
这里还有 first-of-type

2024-09-19 06:47 UTC, eternalsky commented on components/form/__tests__/validate-spec.tsx
> +        cy.get('.next-form-item-help:first-of-type').should('have.text', 'min is 10');
这里还有 first-of-type

2024-09-19 06:47 UTC, eternalsky commented on components/form/__tests__/validate-spec.tsx
> +        cy.get('.next-form-item-help:first-of-type').should('have.text', 'min length is 10');
这里还有 first-of-type

2024-09-19 06:47 UTC, eternalsky commented on components/form/enhance.tsx
> +                (getCfgFromProps(props, 'minmaxLengthTrigger') as string | undefined) ||
这里为啥要重新 as 呢？还是类型对不上，对不上强行对上就没有意义了。

2024-09-19 07:58 UTC, FairyYang commented on components/form/enhance.tsx
> +                (getCfgFromProps(props, 'minmaxLengthTrigger') as string | undefined) ||
这里类型没办法对上，itemprops的minmaxLengthTrigger是string | Array<string>;，Field里的trigger是string
![image](https://github.com/user-attachments/assets/473c1f8b-bb77-4b2c-b24d-e44ff5c96e40)

2024-09-23 01:43 UTC, eternalsky approved these changes

2024-09-23 01:44 UTC, merged