fix(DatePicker2): check disabledDate after clicking ok, close #3801
alibaba-fusion/next pull request #4870
Opened 2024-06-21 03:16 UTC by FairyYang

2024-06-21 06:51 UTC, eternalsky requested changes

2024-06-21 06:51 UTC, eternalsky commented on components/date-picker2/__tests__/index-spec.js
> +});
这个改动好像没有意义

2024-06-21 06:51 UTC, eternalsky commented on components/date-picker2/picker.jsx
> +            checkedValue = Array.isArray(inputValue) ? [null, null] : null;
这里感觉逻辑应该是不响应，而不是赋一个新值上去，赋新值上去还要考虑老的值还要保留，而不是直接就是 null 了。或者 ok 按钮置灰

2024-06-21 06:51 UTC, eternalsky requested changes

2024-06-21 06:51 UTC, eternalsky commented on components/date-picker2/__tests__/index-spec.js
> +            assert.deepEqual(getStrValue(), ['', '']);
这里没有考虑 RangePicker 原本有值的情况

2024-06-28 01:55 UTC, eternalsky requested changes

2024-06-28 01:55 UTC, eternalsky commented on components/date-picker2/__tests__/index-spec.js
> +                    disabledDate={date => +date < +new Date()}
new Date 是每天都在变的。。

2024-06-28 01:55 UTC, eternalsky commented on components/date-picker2/picker.jsx
> +        if(!valuesFiltered.length) {
格式化问题

2024-06-28 01:55 UTC, eternalsky commented on components/date-picker2/picker.jsx
> +        const valuesFiltered = values.filter(value => !!value);
这里为什么额外又增加了一个过滤逻辑呢

2024-06-28 01:55 UTC, eternalsky commented on components/date-picker2/__tests__/index-spec.js
> +            wrapper = mount(
这个 tc 是专门测试 disabled 这个 props 的，放在这里不太合适，而且这个 tc mount/unmount 的次数已经很多了，从 tc 的执行时间的角度考虑，也不应该放在这里了~

2024-06-28 01:56 UTC, eternalsky commented on components/date-picker2/__tests__/index-spec.js
> +                <RangePicker
不止级联选择，单个选择，tc 也应该覆盖

2024-06-28 07:15 UTC, FairyYang commented on components/date-picker2/picker.jsx
> +        const valuesFiltered = values.filter(value => !!value);
因为测试用例会报错
![image](https://github.com/alibaba-fusion/next/assets/21052604/c244c02e-c8c0-4bfd-b6df-ee6f48a7d249)

2024-07-01 07:21 UTC, eternalsky approved these changes

2024-07-01 07:24 UTC, merged