Refactor pagination
alibaba-fusion/next pull request #4874
Opened 2024-07-01 11:48 UTC by caozhong1996

close: #4598

2024-07-25 02:55 UTC, eternalsky requested changes

2024-07-25 02:55 UTC, eternalsky commented on components/pagination/__docs__/demo/control/index.tsx
> +    constructor(props: any) {
demo 上是给用户看的，这里不要出现 any，这里可以参考一下其他组件，去掉 constructor，这样 props 和 state 也不需要额外定义了。

2024-07-25 02:55 UTC, eternalsky commented on components/pagination/__docs__/theme/index.tsx
> +/* eslint-disable */
无用的注释可以去掉了。

2024-07-25 02:55 UTC, eternalsky commented on components/pagination/__tests__/a11y-spec.tsx
>  /* eslint-disable no-undef, react/jsx-filename-extension */
此处同上，无用的 eslint disable 都可以去掉了。

2024-07-25 02:55 UTC, eternalsky commented on components/pagination/__tests__/a11y-spec.tsx
>      it.skip('should not have any violations when various pageSizeSelector', async () => {
这里可以试下 skip 是不是可以拿掉了。

2024-07-25 02:55 UTC, eternalsky commented on components/pagination/__tests__/index-spec.tsx
> +        cy.wrap(() => {
为了 cy 的时序的话，这里应该用的是 cy.then

2024-07-25 02:55 UTC, eternalsky commented on components/pagination/__tests__/index-spec.tsx
> +        cy.wrap(() => {
下同

2024-07-25 02:55 UTC, eternalsky commented on components/pagination/__tests__/index-spec.tsx
> +        // 由于输入不合法，无法触发 onChange，因此无法断言
触发不了也可以断言啊，可以断言函数不触发。使用 cy.spy，参考其他组件和文档

2024-07-25 02:55 UTC, eternalsky commented on components/pagination/__tests__/index-spec.tsx
> +                    expect(size).to.equal(currentPageSize);
这个 expect 能触发到吗，这里是回调，可能用例都跑完了。正常来讲用该是用 cy.spy 之后，在最后断言 called

2024-07-25 02:55 UTC, eternalsky commented on components/pagination/__tests__/index-spec.tsx
> +                    expect(size).to.equal(currentPageSize);
上下类似情况不赘述，要确保所有的 expect 都是真实跑过的。

2024-07-25 02:55 UTC, eternalsky commented on components/pagination/index.tsx
> +import ConfigProvider from '../config-provider';
不要修改逻辑

2024-07-25 02:55 UTC, eternalsky commented on components/pagination/pagination.tsx
> +        this.setState(newState as PaginationState);
这里应该不需要 as

2024-07-25 02:55 UTC, eternalsky commented on components/pagination/pagination.tsx
> +        const isCurrent = index === current;
不要修改逻辑，如果这里类型不对，可以 ts-expect-error 并说明 error 原因

2024-07-25 02:55 UTC, eternalsky commented on components/pagination/pagination.tsx
> +                aria-label={locale.inputAriaLabel as string}
这里不需要 as string，而是 types locale 属性需要详细指定，可以参考一下其他组件

2024-07-25 02:55 UTC, eternalsky commented on components/pagination/pagination.tsx
> +            props.href = link.replace('{page}', `${index}`);
同上，不要修改逻辑

2024-07-25 02:55 UTC, eternalsky commented on components/pagination/pagination.tsx
> +            const halfCount = Math.floor(othersCount / 2);
同上

2024-07-25 02:55 UTC, eternalsky commented on components/pagination/pagination.tsx
> +                    if (typeof item === 'object') {
同上

2024-07-25 02:55 UTC, eternalsky commented on components/pagination/pagination.tsx
> +                aria-label={locale.selectAriaLabel as string}
同上

2024-07-25 02:55 UTC, eternalsky commented on components/pagination/pagination.tsx
> +                    if (typeof item === 'object') {
同上

2024-07-25 02:55 UTC, eternalsky commented on components/pagination/pagination.tsx
> +            [className as string]: !!className,
这里不要 as，去空可以用 ！

2024-07-25 02:55 UTC, eternalsky commented on components/pagination/pagination.tsx
> -export default ConfigProvider.config(polyfill(Pagination));
不要修改逻辑

2024-07-25 02:55 UTC, eternalsky commented on components/pagination/types.ts
> +export default class Pagination extends React.Component<PaginationProps, PaginationState> {}
这个可以删除了

2024-07-25 02:55 UTC, eternalsky commented on components/pagination/types.ts
> +export interface PaginationProps extends HTMLAttributesWeak, CommonProps {
这里应该加入 @api 用来生成 doc，这里改好之后应该运行一下 npm run api xxx 来重新生成一下文档

2024-07-25 02:55 UTC, eternalsky commented on components/pagination/types.ts
> +     */
这里应该专门指定 locale，参考其他组件

2024-08-09 06:44 UTC, caozhong1996 commented on components/pagination/__tests__/index-spec.tsx
> +                    expect(size).to.equal(currentPageSize);
仔细看过，这种情况是可以触发的，其他用例也都改了下

2024-08-09 06:47 UTC, caozhong1996 commented on components/pagination/pagination.tsx
> +        this.setState(newState as PaginationState);
这里好像没有太好的办法，不用as只能额外加一个current，但是那就改逻辑了

2024-08-09 09:28 UTC, eternalsky commented on components/pagination/pagination.tsx
> +        this.setState(newState as PaginationState);
> 这里好像没有太好的办法，不用as只能额外加一个current，但是那就改逻辑了

没明白，current 不是本来就是 state 的一部分吗

2024-08-12 02:40 UTC, caozhong1996 commented on components/pagination/pagination.tsx
> +        this.setState(newState as PaginationState);
因为对于 newState 来说，current 是可选的，和 state 的类型定义不一致：
````ts
interface PaginationState {
    current: number;
    currentPageSize: number;
    inputValue: string;
}
````
所以，要么就使用 as ，要么就加一个初始化的 current ，但是这样又破坏了原来的逻辑 
````diff
const newState = {
   currentPageSize: pageSize,
+  current: this.state.current
};

const totalPage = getTotalPage(this.props.total, pageSize);
if (this.state.current > totalPage) {
   newState.current = totalPage;
}

this.setState(newState);
````

2024-08-13 01:57 UTC, eternalsky requested changes

2024-08-13 01:57 UTC, eternalsky commented on components/pagination/__docs__/demo/control/index.tsx
> +    handleChange(current: number) {
这里应该用箭头函数绑定 this，否则应该会报错吧

2024-08-13 01:57 UTC, eternalsky commented on components/pagination/__tests__/index-spec.tsx
> +        // @ts-expect-error-next
这里为什么是 expect error？如果需要 expect error 需要在注释后跟上原因

2024-08-13 01:57 UTC, eternalsky commented on components/pagination/__tests__/index-spec.tsx
> +            cy.mount(<Pagination shape={shape} />)
这里感觉使用 should('have.text', xxx) 更简洁吧。下同

2024-08-13 01:57 UTC, eternalsky commented on components/pagination/__tests__/index-spec.tsx
> +        cy.wrap(() => {
这里好像没有改

2024-08-13 01:57 UTC, eternalsky commented on components/pagination/__tests__/index-spec.tsx
> +                    expect(size).to.equal(currentPageSize);
即使能触发，这样的触发也是不稳定的，毕竟这里是回调，最后没有断言把时间等住的话，这里不触发也是很有可能，这样测试用例就不会不太稳定，要避免这个情况，最后还是使用 should('be.called') 断言是比较好的。其他地方相同

2024-08-13 01:57 UTC, eternalsky commented on components/pagination/pagination.tsx
> +        this.setState(newState as PaginationState);
setState 的泛型可以指定设置的 key

2024-08-13 01:57 UTC, eternalsky commented on components/pagination/pagination.tsx
> +        // @ts-expect-error be compatible with old logic
这个注释没看懂什么意思，什么是和老逻辑兼容？

2024-08-13 01:57 UTC, eternalsky commented on components/pagination/pagination.tsx
> +                    // @ts-expect-error be compatible with old logic
这个说明等于没说，这里说明的原因，应该是解释这里为什么 expect error，具体的原因是什么

2024-08-13 01:57 UTC, eternalsky commented on components/pagination/pagination.tsx
> +                aria-label={locale.selectAriaLabel as string}
这里没改

2024-08-13 01:57 UTC, eternalsky commented on components/pagination/pagination.tsx
> +                    // @ts-expect-error be compatible with old logic
其他地方类似，不再赘述

2024-08-13 01:57 UTC, eternalsky commented on components/pagination/pagination.tsx
> +                    if (typeof item === 'object') {
这里没改

2024-08-20 02:01 UTC, eternalsky requested changes

2024-08-20 02:03 UTC, eternalsky requested changes

2024-08-20 02:03 UTC, eternalsky commented on components/pagination/__tests__/index-spec.tsx
> +        const onChangeCalledSpy = cy.spy(() => {});
这里不需要写 () => {}

2024-08-20 02:03 UTC, eternalsky commented on components/pagination/__tests__/index-spec.tsx
> +        const onChangeSpy = cy.spy(index => {
此处同

2024-08-20 02:03 UTC, eternalsky commented on components/pagination/__tests__/index-spec.tsx
> +        const onChangeSpy = cy.spy(() => {});
同上

2024-08-20 02:03 UTC, eternalsky commented on components/pagination/__tests__/index-spec.tsx
> +            expect(size).to.equal(currentPageSize);
同上

2024-08-20 02:03 UTC, eternalsky commented on components/pagination/__tests__/index-spec.tsx
> +            expect(size).to.equal(currentPageSize);
同上

2024-08-30 06:23 UTC, eternalsky approved these changes

2024-08-30 06:23 UTC, merged