refactor(Breadcrumb): Document optimization & Upgrade testing tools and optimize use cases & rename to ts
alibaba-fusion/next pull request #4876
Opened 2024-07-03 09:24 UTC by luolin-ck

close #4567

2024-07-23 01:31 UTC, eternalsky requested changes

2024-07-23 01:31 UTC, eternalsky commented on components/breadcrumb/__tests__/a11y-spec.tsx
>  /* eslint-disable no-undef, react/jsx-filename-extension */
这个注释可以去掉了

2024-07-23 01:31 UTC, eternalsky commented on components/breadcrumb/index.tsx
> +        state: { prevMaxNode: BreadcrumbProps['maxNode'] }
这里的写法不准确，props 和 state 并不只有这些属性，而应该是组件的 props 和 state 类型。

2024-07-23 01:31 UTC, eternalsky commented on components/breadcrumb/index.tsx
> +    renderEllipsisNodeWithMenu(children: React.ReactNode, breakpointer: number) {
ReactNode 应从 React 中解构取出，其他地方同

2024-07-23 01:31 UTC, eternalsky commented on components/breadcrumb/index.tsx
> +                {...(popupProps as DropdownProps)}
这里为什么需要 as？

2024-07-23 01:31 UTC, eternalsky commented on components/breadcrumb/index.tsx
> +        const maxNode = this.state.maxNode as number;
这个改动的意义是什么？如果 maxNode  应该是 number，应该从定义他的地方设置类型。

2024-07-23 01:31 UTC, eternalsky commented on components/breadcrumb/index.tsx
> +        const length: number = Children.count(children);
count 返回的类型不就是 number 吗~ 这里为什么要特殊指定一下

2024-07-23 01:31 UTC, eternalsky commented on components/breadcrumb/index.tsx
> +        const BreadcrumbComponent = component as unknown as React.FC<BreadcrumbProps>;
这里为什么要做强制类型转换？

2024-07-23 01:31 UTC, eternalsky commented on components/breadcrumb/index.tsx
> +        const BreadcrumbComponent = component as unknown as React.FC<BreadcrumbProps>;
component 不是就应该定义成带 BreadcrumbProps 的组件吗。

2024-07-23 01:31 UTC, eternalsky commented on components/breadcrumb/index.tsx
> +        if ('maxNode' in others) {
这里改动原有逻辑了，这次的策略是不改动原有逻辑

2024-07-23 01:31 UTC, eternalsky commented on components/breadcrumb/types.ts
> +    children?: Array<React.ReactNode> | React.ReactNode;
既然 children 只能是 Breadcrumb.Item，那类型里为什么不直接限定住呢。

2024-07-23 01:31 UTC, eternalsky commented on components/breadcrumb/types.ts
> +     * @en Children components, hsould be an Breadcrumb.Item
should 写错了

2024-07-23 01:31 UTC, eternalsky commented on components/breadcrumb/types.ts
> +export default class Breadcrumb extends React.Component<BreadcrumbProps> {
这个应该删除了

2024-07-23 01:31 UTC, eternalsky commented on components/breadcrumb/index.tsx
> +export type { BreadcrumbProps } from './types';
这里还应该输出 ItemProps

2024-07-25 06:17 UTC, eternalsky requested changes

2024-07-25 06:17 UTC, eternalsky commented on components/breadcrumb/index.tsx
> +        // @ts-expect-error 属性"maxNode"不存在于类型others上
中英文之间空格，另外这里有个带引号有不带也有点奇怪，建议统一

2024-07-25 06:17 UTC, eternalsky commented on components/breadcrumb/types.ts
> +        | Array<React.ReactElement<ItemProps> | string | boolean | null>
还可以是 string 和 boolean 吗

2024-07-25 06:32 UTC, eternalsky requested changes

2024-07-25 06:32 UTC, eternalsky commented on components/breadcrumb/item.tsx
> +    static Separator({ prefix, children }: { prefix?: string; children: React.ReactNode }) {
这里也还有 React.xxx 的情况，可以再整体看一下。这个文件之前没有 import React 也有问题，可以补一下。

2024-07-25 06:32 UTC, eternalsky commented on components/breadcrumb/item.tsx
> +    static Separator({ prefix, children }: { prefix?: string; children: React.ReactNode }) {
除了 types 之外，其他的地方，都应解构获取 type

2024-07-25 06:53 UTC, luolin-ck commented on components/breadcrumb/types.ts
> +        | Array<React.ReactElement<ItemProps> | string | boolean | null>
const flag = false;
ReactDOM.render(
    <Breadcrumb>
        {flag && <Breadcrumb.Item link="javascript:void(0);">Home</Breadcrumb.Item>}
        <Breadcrumb.Item link="javascript:void(0);">All Categories</Breadcrumb.Item>
        <Breadcrumb.Item link="javascript:void(0);">Women’s Clothing</Breadcrumb.Item>
        <Breadcrumb.Item link="javascript:void(0);">Blouses & Shirts</Breadcrumb.Item>
        <Breadcrumb.Item>
            T-shirts <b>78,999</b> Results
        </Breadcrumb.Item>
    </Breadcrumb>,
    mountNode
);还是有boolean的用法的

2024-07-29 11:58 UTC, merged