fix(Upload): support itemRender on Dragger, close #4840
alibaba-fusion/next pull request #4880
Opened 2024-07-08 07:06 UTC by FairyYang

2024-07-24 01:20 UTC, eternalsky requested changes

2024-07-25 06:29 UTC, eternalsky requested changes

2024-07-25 06:29 UTC, eternalsky commented on components/upload/__docs__/demo/extra/index.tsx
> +const itemRender: CardProps['itemRender'] = (file, obj) => {
这个 obj 感觉命名有些随意，我觉得可以保持原样，或者起个更有意义的。

2024-07-25 06:29 UTC, eternalsky commented on components/upload/list.tsx
> +            /* eslint-disable no-lonely-if */
这个 eslint-disable 感觉没有用处吧

2024-07-25 06:29 UTC, eternalsky commented on components/upload/list.tsx
> +                // 不处理上传态和选择态，太过复杂
这个注释我也一直没看懂，这里跟是不是上传态有啥关系

2024-07-25 06:29 UTC, eternalsky commented on components/upload/types.ts
> +     * @en Customize success and failure list rendering, only in listType is card
英文没改，改完记得重新 run api

2024-07-25 06:29 UTC, eternalsky commented on components/upload/types.ts
> +     * @en Customize success and failure list rendering，only in listType is card
同上

2024-07-25 06:53 UTC, FairyYang commented on components/upload/list.tsx
> +            /* eslint-disable no-lonely-if */
这里没有的话，会TS报错，else语句中，不能只有if else语句

2024-07-29 07:40 UTC, eternalsky requested changes

2024-07-29 07:40 UTC, eternalsky commented on components/upload/__docs__/index.en-us.md
> +IE10+ 支持。继承 Upload 的 API，除非特别说明
这里中文的 doc 也变成英文了。

2024-07-29 07:40 UTC, eternalsky commented on components/upload/__docs__/index.en-us.md
> +IE10+ 支持。继承 Upload 的 API，除非特别说明
也尝试用 - 间隔一下中英文

2024-07-29 11:56 UTC, eternalsky approved these changes

2024-07-29 11:56 UTC, merged