Refactor/virtual list
alibaba-fusion/next pull request #4906
Opened 2024-08-01 08:12 UTC by eamonzym

close #4623

2024-08-07 02:44 UTC, eternalsky requested changes

2024-08-07 02:44 UTC, eternalsky commented on components/virtual-list/__docs__/demo/item-size-getter/index.tsx
> +            const instance = (this.refs.virtual as InstanceType<typeof VirtualList>).getInstance();
refs.xxx 的用法已经 deprecated 了，这次可以直接改成 React 推荐的形式。

2024-08-07 02:44 UTC, eternalsky commented on components/virtual-list/__tests__/a11y-spec.tsx
> +/* eslint-disable no-undef, react/jsx-filename-extension */
无用的注释可以去掉。

2024-08-07 02:44 UTC, eternalsky commented on components/virtual-list/__tests__/a11y-spec.tsx
> +        cy.mount(<VirtualList>{generateData(10)}</VirtualList>);
这里改成 cy.mount 就没有意义了，还是得用 testReact 才能测 a11y。

2024-08-07 02:44 UTC, eternalsky commented on components/virtual-list/__tests__/a11y-spec.tsx
> +        cy.mount(<VirtualList>{generateData(10)}</VirtualList>);
参考其他组件

2024-08-07 02:44 UTC, eternalsky commented on components/virtual-list/__tests__/index-spec.tsx
> +        // 这里的 wait 是有必要的
说一下必要性？

2024-08-07 02:44 UTC, eternalsky commented on components/virtual-list/types.ts
> +    [key: string]: unknown; // 添加索引签名
这里为什么需要加一个通用索引？

2024-08-07 02:44 UTC, eternalsky commented on components/virtual-list/types.ts
> +     * @en the parent render function
@en 应该紧跟中文说明

2024-08-07 02:44 UTC, eternalsky commented on components/virtual-list/types.ts
> +export default class VirtualList extends React.Component<VirtualListProps, VirtualListState> {}
这个应该删除了。

2024-08-07 02:44 UTC, eternalsky commented on components/virtual-list/virtual-list.tsx
> +const isEqualSubset = (a: VirtualListState, b: VirtualListState) => {
这个明显类型写窄了吧，之前有提过，类型不是以谁调用来决定的，而应该是以函数的实现来决定的。

2024-08-07 02:44 UTC, eternalsky commented on components/virtual-list/virtual-list.tsx
> +    { children, minSize }: VirtualListProps
这里和上面有类似的问题

2024-08-07 02:44 UTC, eternalsky commented on components/virtual-list/virtual-list.tsx
> +    const length = children && (children as Array<ReactElement>).length;
这里也是因为上面定义的类型不对导致

2024-08-07 02:44 UTC, eternalsky commented on components/virtual-list/virtual-list.tsx
> +        const style = { position: 'relative' } as CSSProperties;
前置定义比后置好，应该是 style： CSSProperties

2024-08-07 02:44 UTC, eternalsky commented on components/virtual-list/types.ts
> +    children?: React.ReactElement | Array<React.ReactElement | undefined | null>;
从多个实现的地方来看 children 只能是 Array，单个的出现在什么情况下？

2024-08-07 07:19 UTC, eamonzym commented on components/virtual-list/types.ts
> +    children?: React.ReactElement | Array<React.ReactElement | undefined | null>;
单个情况会在select组件里出现。virtuallist单个情况下，测试用例通过，无报错，但是代码逻辑并没有考虑到单个情况，只是恰巧没问题，这里对children使用到length的情况用// @ts-expect-error 处理

2024-08-07 09:23 UTC, eternalsky requested changes

2024-08-07 09:23 UTC, eternalsky commented on components/virtual-list/__docs__/demo/item-size-getter/index.tsx
> +class App extends React.Component<VirtualListProps> {
这个定义不正确吧，App 并没有接受任何 props，他的 props 不是 VirtualListProps。另外初始化 virtualListRef 的过程直接和定义放在一起就可以了，这样还少的去额外定义一次他的类型，直接就可以推导出来。constructor 也就用不到了。

2024-08-07 09:23 UTC, eternalsky commented on components/virtual-list/__docs__/demo/item-size-getter/index.tsx
> +            const instance = this.virtualListRef.current!.getInstance();
这里应该先判断一下 current 是不是存在再调用

2024-08-07 09:23 UTC, eternalsky commented on components/virtual-list/__tests__/index-spec.tsx
> +        // 这里的 wait 是有必要的 滚动到第五十个元素，需要等待滚动到指定位置
需要等待滚动到第五十个元素，应该用 get 去等待，而不是 wait 100，因为 wait 一个固定时间是不稳定的，并不能保证每次都有。而且 get 是等待四秒的，并且 get 只认为 visibile 时才是真正能 get 的情况，因此完全可以 cover 这个场景。

2024-08-07 09:23 UTC, eternalsky commented on components/virtual-list/__tests__/index-spec.tsx
> +                expect(parseInt(text)).to.be.above(40);
parseInt  应该指定一下第二个参数，明确转换规则。

2024-08-07 09:23 UTC, eternalsky commented on components/virtual-list/types.ts
> +export type VirtualListState = Record<'size' | 'from', number>;
这样写不利于后续 State 扩展，还是写成 interface 比较好。

2024-08-07 09:23 UTC, eternalsky commented on components/virtual-list/virtual-list.tsx
> +    // @ts-expect-error children 未考虑非数组是单个ReactElement的情况
中英文空格

2024-08-07 09:23 UTC, eternalsky commented on components/virtual-list/types.ts
> +     * @en the minimum number of items to be loaded
有多个 defaultValue 都没有写上，要按照实现把 defaultValue 补充一下

2024-08-07 09:23 UTC, eternalsky commented on components/virtual-list/types.ts
> +        ref: (
这个 ref 感觉写的有问题，太复杂了。另外好像对 ref 的返回值也没有啥要求吧，为啥这里返回这么一大段

2024-08-07 09:23 UTC, eternalsky commented on components/virtual-list/types.ts
> +    ) => React.ReactElement;
这里应该是 ReactNode 吧，从下面的实现看，没看到哪里要求只能是 ReactElement

2024-08-07 09:23 UTC, eternalsky commented on components/virtual-list/types.ts
> +        ref: (
instance 感觉应该是 任意 ReactInstance 都是可以的，并没有限制必须是 UL 或者 menu。这里还是犯了看调用而不是看实现写类型的问题。

2024-08-07 09:35 UTC, eternalsky requested changes

2024-08-07 09:35 UTC, eternalsky commented on components/virtual-list/virtual-list.tsx
> +    items:
这个 items 需要写这么复杂吗

2024-08-07 09:35 UTC, eternalsky commented on components/virtual-list/virtual-list.tsx
> +            // @ts-expect-error children 未考虑非数组是单个ReactElement的情况
中英文空格

2024-08-07 09:35 UTC, eternalsky commented on components/virtual-list/virtual-list.tsx
> +                const ulRef = findDOMNode(this.items as ReactInstance) as Element;
这里应该是前置定义比较好，另外既然已经是 ulRef，那这里 Element 其实可以更进一步到 HTMLElement

2024-08-07 09:35 UTC, eternalsky commented on components/virtual-list/virtual-list.tsx
> +        const { children, props = {} as { children: Array<ReactElement> } } = this.items as {
props 这里为什么也要 as

2024-08-07 09:35 UTC, eternalsky commented on components/virtual-list/virtual-list.tsx
> +        const { children, props = {} as { children: Array<ReactElement> } } = this.items as {
从这个实现来看，其实 this.items 的实现其实基本上就可以定义出来了，这里所有的定义都应该在 items 定义那里写好，而不是在这里再 as 成这个或者那个。

2024-08-07 09:35 UTC, eternalsky commented on components/virtual-list/types.ts
> +        ref: (
return 的是 this.items , this.items 就是 instance。所以这里应该使用泛型统一起来。

2024-08-09 06:20 UTC, eternalsky requested changes

2024-08-20 02:42 UTC, eternalsky approved these changes

2024-08-20 02:42 UTC, merged