refactor(Balloon): convert to TypeScript, impove docs and tests, close#4565
alibaba-fusion/next pull request #4915
Opened 2024-08-20 03:20 UTC by FairyYang

…e#4565

2024-08-30 10:00 UTC, eternalsky requested changes

2024-08-30 10:00 UTC, eternalsky commented on components/balloon/types.ts
> +    v2?: boolean;
v1 和 v2 配置，建议参考 Popup 的方式区别开，因为有些属性是 v2 专属的，而有些属性又是 v2 下 deprecated 掉的，这部分应该区别开，否则给出的提示是不正确的。

2024-09-04 03:50 UTC, FairyYang commented on components/balloon/__tests__/balloon-v2-spec.tsx
> +        expect(onClose.calledOnce);
这个没理解是什么意思，should能判断事件被触发次数吗

2024-09-04 07:49 UTC, FairyYang commented on components/balloon/balloon.tsx
> +    _onClose: MouseEventHandler<HTMLAnchorElement> = function (e) {
![image](https://github.com/user-attachments/assets/05bcfec4-e582-4c3b-a6ea-b095be289f8c)
因为要赋值给a标签的onClick事件

2024-09-05 03:22 UTC, eternalsky requested changes

2024-09-05 03:22 UTC, eternalsky commented on components/balloon/types.ts
> +export interface TooltipProps extends HTMLAttributesWeak, CommonProps {
Tooltip 不是也是要区分 v1 和 v2 吗

2024-09-05 03:22 UTC, eternalsky commented on components/balloon/types.ts
> +     * [v2] 是否进行自动位置调整，默认自动开启
v1 版本里有很多 v2 才有的属性

2024-09-05 03:22 UTC, eternalsky commented on components/balloon/index.tsx
> +                deprecated('text', 'children', 'Tooltip');
这个属性在 types 里没有体现

2024-09-05 03:22 UTC, eternalsky commented on components/balloon/index.tsx
> +            deprecated(
这个属性在 types 里没有体现

2024-09-05 03:22 UTC, eternalsky commented on components/balloon/index.tsx
>              deprecated('alignment', 'alignEdge', 'Balloon');
这个属性在 types 里没有体现

2024-09-05 03:22 UTC, eternalsky commented on components/balloon/__docs__/index.md
> +export type BalloonProps = BalloonV1Props | BalloonV2Props;
这个 README 已经没法用了。。

2024-09-05 04:10 UTC, FairyYang commented on components/balloon/__tests__/balloon-spec.tsx
> +                cy.get('.next-balloon').should('exist');
已经修改过了，其他文件的settimeout也修改了
![image](https://github.com/user-attachments/assets/02b56bbb-4d0a-4daa-a69e-2a1ee91d02ee)

2024-09-05 04:13 UTC, FairyYang commented on components/balloon/__tests__/balloon-v2-spec.tsx
> +            cy.get('.next-balloon').should('exist');
这里已经修改过了  是不是看错文件了？

2024-09-05 04:17 UTC, FairyYang commented on components/balloon/balloon.tsx
> +    _onClose: MouseEventHandler<HTMLAnchorElement> = function (e) {
我理解e应该是MouseEvent，但是这样a标签onclick事件会报ts错误
![image](https://github.com/user-attachments/assets/8607415a-5471-4ee4-a81f-4f1f377ceff8)

![image](https://github.com/user-attachments/assets/b73e2567-6c3e-4605-a842-98995a38fb9c)

2024-09-05 06:28 UTC, FairyYang commented on components/balloon/types.ts
> +     * [v2] 是否进行自动位置调整，默认自动开启
如果在V1中去掉v2才有的属性的话，会有ts错误
![image](https://github.com/user-attachments/assets/ff8f7b96-f117-4e5d-8df8-4c6dd045db91)

2024-09-05 12:03 UTC, eternalsky commented on components/balloon/balloon.tsx
> +    _onClose = function (e: MouseEvent) {
既然只是改 e，就没必要把成员方法改成成员属性了

2024-09-05 12:03 UTC, eternalsky commented on components/select/__docs__/demo/basic/index.tsx
> +        <Select.AutoComplete
这个还没有改

2024-09-05 12:11 UTC, eternalsky requested changes

2024-09-05 12:11 UTC, eternalsky commented on components/balloon/__tests__/tooltip-v2-spec.tsx
> +    });
貌似少了一个 tc，trigger is disabled button, hover enter and leave, popup should resolve

2024-09-05 12:11 UTC, eternalsky commented on components/balloon/__tests__/tooltip-spec.tsx
> +    // trigger 不传，默认用空的<span></span>填充
貌似少了一个 tc trigger is disabled button, hover enter and leave, popup should resolve

2024-09-05 12:11 UTC, eternalsky commented on components/balloon/__docs__/index.md
> +### Balloon V1
v1 是空的，v2 里只有 v2 的属性，其他的属性看不到了。。

2024-09-05 12:11 UTC, eternalsky commented on components/balloon/__docs__/index.md
> +### Balloon V1
另外 Balloon.tooltip 的文档也没有了

2024-09-05 12:11 UTC, eternalsky commented on components/balloon/__docs__/index.md
> +### Balloon V1
这里不要只是生成就完了，要看一下新生成的内容是否是可用的

2024-09-06 01:53 UTC, FairyYang commented on components/balloon/__tests__/tooltip-v2-spec.tsx
> +    });
这个tc通不过，run start运行下来，也是通不过的

2024-09-06 01:53 UTC, FairyYang commented on components/balloon/__tests__/tooltip-spec.tsx
> +    // trigger 不传，默认用空的<span></span>填充
同上

2024-09-06 02:57 UTC, FairyYang commented on components/balloon/__tests__/tooltip-v2-spec.tsx
> +    });
用例的测试内容是：当传入禁用的button作为触发元素时，鼠标移入时，应该显示气泡。
试过master分支上，npm run start balloon，鼠标移入时不会显示气泡。
Balloon中也有相似的用例，源码是注释掉的，已经删掉了。
所以判定这个用例有问题，可以删掉，
在master分支，运行 npm run test:js balloon时，此用例是通过的。

2024-09-06 03:17 UTC, eternalsky requested changes

2024-09-06 03:17 UTC, eternalsky commented on components/balloon/types.ts
> +export interface TooltipPropsV1 extends HTMLAttributesWeak, CommonProps {
命名上保持一致哈，还是叫xxxV1Props，v2 同

2024-09-06 03:17 UTC, eternalsky commented on components/balloon/__docs__/index.md
> +### Balloon.Tooltip V1
注意看下以前的顺序

2024-09-06 03:17 UTC, eternalsky commented on components/balloon/types.ts
> +    v2?: boolean;
v2 配置项没有区别

2024-09-06 03:17 UTC, eternalsky commented on components/balloon/types.ts
> +    v2?: boolean;
v2 配置项没有区别

2024-09-06 03:17 UTC, eternalsky commented on components/balloon/types.ts
> +    v2?: boolean;
v2 类型没有区别，这样就没有区分的必要了。

2024-09-06 03:17 UTC, eternalsky commented on components/balloon/types.ts
> +    v2?: boolean;
v2 应该放在最前面，否则用户不知道怎么样使用是 v1，怎么样是 v2

2024-09-06 09:26 UTC, eternalsky commented on components/balloon/__tests__/tooltip-v2-spec.tsx
> +    });
这个问题后面我来跟进吧

2024-09-06 09:26 UTC, eternalsky commented on components/balloon/__tests__/tooltip-spec.tsx
> +    // trigger 不传，默认用空的<span></span>填充
这个问题后面我来跟进吧

2024-09-10 01:36 UTC, eternalsky approved these changes

2024-09-10 01:39 UTC, merged