refactor(Card): convert to TypeScript, improve docs and tests, close#4571
alibaba-fusion/next pull request #4917
Opened 2024-08-23 03:51 UTC by FairyYang

2024-08-30 07:53 UTC, eternalsky requested changes

2024-08-30 07:53 UTC, eternalsky commented on components/card/__docs__/demo/divider/index.tsx
> +            <Card.Header {...commonProps} />
去掉意思就不一样了，这个应该是要放在 commonProps 后面

2024-08-30 07:53 UTC, eternalsky commented on components/card/__docs__/demo/divider/index.tsx
> +            <Card.Header {...commonProps} />
同上

2024-08-30 07:53 UTC, eternalsky commented on components/card/__docs__/index.en-us.md
> -### Card.Actions
这里顺序上和以前的保持一致吧，在 types 里通过 @order 控制顺序

2024-08-30 07:53 UTC, eternalsky commented on components/card/collapse-content.tsx
> +                height = (height as number) - (el as Element).getBoundingClientRect().height;
el 应该在定义时声明类型

2024-08-30 07:53 UTC, eternalsky commented on components/card/collapse-content.tsx
> +                height = (height as number) - (el as Element).getBoundingClientRect().height;
这里 height 需要 as 我觉得根本原因在于 contentHeight 的类型太宽，从实现上来看，貌似 contentHeight 如果是 string 时只能是 auto，其他值看起来都似乎有问题的。

2024-08-30 07:53 UTC, eternalsky commented on components/card/header.tsx
> +        const Component = component as React.ElementType;
ElementType 应该解构获得

2024-08-30 07:53 UTC, eternalsky commented on components/card/index.tsx
> +import type {
这里貌似直接 export type from 会写得更简练一些。

2024-08-30 07:53 UTC, eternalsky commented on components/card/types.ts
> +     * @defaultValue 'true'
只有字符串需要引号

2024-08-30 07:53 UTC, eternalsky commented on components/card/types.ts
> +     * @defaultValue 'true'
同上

2024-08-30 07:53 UTC, eternalsky commented on components/card/types.ts
> +     * @defaultValue '120'
同上

2024-08-30 07:53 UTC, eternalsky commented on components/card/types.ts
> +     * 是否带边框  @version 1.24
@version 也是一个 tag，可以直接写在一级，不用刚在标题里。

2024-08-30 07:53 UTC, eternalsky commented on components/card/types.ts
> +    hasBorder?: boolean;
有些默认值貌似加的不全，比如这个，这里应该参考具体实现里的 defaultProps

2024-08-30 07:53 UTC, eternalsky commented on components/card/types.ts
> +    hasBorder?: boolean;
其他有类似情况的也看一下，不再赘述

2024-08-30 07:53 UTC, eternalsky commented on components/card/types.ts
> +     *  @defaultValue 'div'
这里多了一个空格

2024-09-03 04:09 UTC, FairyYang commented on components/card/__docs__/demo/divider/index.tsx
> +            <Card.Header {...commonProps} />
因为commonProps里有title属性，会覆盖title="Simple Card" ，所以去掉了

2024-09-03 04:11 UTC, FairyYang commented on components/card/__docs__/index.en-us.md
> -### Card.Actions
![image](https://github.com/user-attachments/assets/85b7b8ea-1de8-4f53-83a5-e7cc2467e6ff)
types里已经有了

2024-09-03 04:16 UTC, FairyYang commented on components/card/index.tsx
> +import type {
![image](https://github.com/user-attachments/assets/108f732e-ec1c-49f1-b1b9-c67ce2360e94)
文件里没有要export type呀

2024-09-03 07:20 UTC, FairyYang commented on components/card/collapse-content.tsx
> +                height = (height as number) - (el as Element).getBoundingClientRect().height;
contentHeight 为字符串 '300'时，也是生效的，所以是类型string

2024-09-04 06:13 UTC, eternalsky commented on components/card/__docs__/demo/divider/index.tsx
> +            <Card.Header {...commonProps} />
CommonProps 里 title 是一样的，而他这个 demo，明显是希望 title 是不一样的。我觉得放在后面可能会更好

2024-09-04 06:13 UTC, eternalsky commented on components/card/__docs__/index.en-us.md
> -### Card.Actions
types 里虽然有，但是 readme 里的生成顺序还是不对的，估计应该是没有重新生成。

2024-09-04 07:01 UTC, eternalsky requested changes

2024-09-04 07:01 UTC, eternalsky commented on components/card/types.ts
> +     * @en without border
这个英文怎么是 without border？另外注意首字母大写

2024-09-05 02:21 UTC, FairyYang commented on components/card/__docs__/demo/divider/index.tsx
> +            <Card.Header {...commonProps} />
![image](https://github.com/user-attachments/assets/50ef60c2-ee5c-4d93-a40c-d61916cedcea)
commonProps使用的地方有两个，都有 title="Simple Card"，所以对commonProps做了修改

2024-09-05 02:24 UTC, FairyYang commented on components/card/__docs__/index.en-us.md
> -### Card.Actions
已经运行过npm run api card了，还是没有变化，readme是指哪个文件呢

2024-09-05 02:26 UTC, FairyYang commented on components/card/collapse-content.tsx
> +                height = (height as number) - (el as Element).getBoundingClientRect().height;
![image](https://github.com/user-attachments/assets/9c38c453-d8e5-4bfa-9f3b-dbbdd948d1d0)

2024-09-05 02:31 UTC, FairyYang commented on components/card/collapse-content.tsx
> +            const el: Element | Text | null = ReactDOM.findDOMNode(this.footer);
![image](https://github.com/user-attachments/assets/16dae0bc-92a8-4f97-92d4-2186a2b3f671)
![image](https://github.com/user-attachments/assets/f67b06a6-c4ba-435d-ba39-a8cd8a26054f)
footer的类型是HTMLDivElement，ReactDOM.findDOMNode()的返回值没有判断出类型。最后还是用了as

2024-09-05 02:34 UTC, FairyYang commented on components/card/index.tsx
> +import type {
已经修改了，上面的截图是错误的文件

2024-09-05 03:24 UTC, eternalsky commented on components/card/__docs__/index.en-us.md
> -### Card.Actions
> 已经运行过npm run api card了，还是没有变化，readme是指哪个文件呢

readme 指的就是 index.md

2024-09-05 03:29 UTC, eternalsky commented on components/card/index.tsx
> +            deprecated('titleBottomLine', 'showHeadDivider', 'Card');
deprecated 的属性在 types 里没有体现

2024-09-05 03:29 UTC, eternalsky commented on components/card/collapse-content.tsx
> +            const el: Element | Text | null = ReactDOM.findDOMNode(this.footer);
这里用 as 是正确的，as 不是不能用，只是要限制使用场合，只有在明确知道类型收窄，但是又无法添加类型守卫时可以使用。

2024-09-05 07:41 UTC, eternalsky approved these changes

2024-09-05 07:42 UTC, merged