fix(Overlay): overlay support SSR, close #4205
alibaba-fusion/next pull request #4923
Opened 2024-08-30 06:17 UTC by FairyYang

2024-09-04 04:00 UTC, eternalsky requested changes

2024-09-04 04:00 UTC, eternalsky commented on components/overlay/position.tsx
>          this.setPosition();
setPosition  也有 dom 相关的操作，也需要在判断范围内。

2024-09-04 10:14 UTC, FairyYang commented on components/overlay/position.tsx
>          this.setPosition();
![image](https://github.com/user-attachments/assets/585118ad-7182-49f7-9646-8cfdd887dee1)
在这里新增了处理

2024-09-05 03:39 UTC, eternalsky requested changes

2024-09-05 03:39 UTC, eternalsky commented on components/overlay/popup.tsx
> +            if (typeof document !== 'undefined') return document.body;
这里有必要加吗

2024-09-05 03:39 UTC, eternalsky commented on components/overlay/overlay.tsx
> +                if (typeof document === 'undefined') return;
这里没必要加，handleClick 已经是在 ssr 周期以外了

2024-09-05 03:58 UTC, FairyYang commented on components/overlay/popup.tsx
> +            if (typeof document !== 'undefined') return document.body;
我理解是要的，因为在服务器端渲染（SSR）的过程中，React 组件的静态属性（如 static defaultProps）会在服务器端执行。

2024-09-05 07:44 UTC, eternalsky commented on components/overlay/popup.tsx
> +            if (typeof document !== 'undefined') return document.body;
执行的是函数声明，而不是函数本身的执行，函数本身不执行就没有问题。

2024-09-05 07:49 UTC, eternalsky requested changes

2024-09-05 07:49 UTC, eternalsky commented on components/overlay/overlay.tsx
> +                if (
这里去掉 document 了之后好像就没有拆成两个 if 的意义了

2024-09-05 07:49 UTC, eternalsky commented on components/overlay/overlay.tsx
> +            if (el.tagName === 'HTML' && typeof document !== 'undefined') {
这里感觉也没有必要，都不是 ssr 周期里的

2024-09-05 11:08 UTC, eternalsky approved these changes

2024-09-05 11:08 UTC, merged