refactor(TimePicker2): convert to TypeScript, impove docs and tests, close #4616
alibaba-fusion/next pull request #4949
Opened 2024-09-26 09:37 UTC by FairyYang

遇到个问题，当type: range时，disabledHours 需要返回number[]，panel的代码逻辑是这么实现的。实际使用过，确实如此。

2024-10-10 05:39 UTC, eternalsky commented
> 遇到个问题，当type: range时，disabledHours 需要返回number[]，panel的代码逻辑是这么实现的。实际使用过，确实如此。

这个只是描述一个事实，问题是什么？

2024-10-10 05:39 UTC, FairyYang commented
我收到了

2024-10-10 06:28 UTC, FairyYang commented
问题是，disabledHours在旧的doc里，类型是 (index?: number) => boolean，新增的类型是：(index?: number) => boolean | number[]

2024-10-10 06:51 UTC, eternalsky commented
> 问题是，disabledHours在旧的doc里，类型是 (index?: number) => boolean，新增的类型是：(index?: number) => boolean | number[]

以实际的实现逻辑为准

2024-10-12 08:36 UTC, eternalsky requested changes

2024-10-12 08:36 UTC, eternalsky commented on components/time-picker2/prop-types.ts
> +                        datejs(v as string | number | Date | Dayjs | null | undefined).isValid() ||
这里直接应用 dayjs 的类型 configTypre 就好了吧，没必要再写一遍。

2024-10-12 08:36 UTC, eternalsky commented on components/time-picker2/time-picker.tsx
> +
这里多了一个空行

2024-10-12 08:36 UTC, eternalsky commented on components/time-picker2/time-picker.tsx
> +    value: PropTypes.oneOfType([PropTypes.func, checkDateValue as PropTypes.Validator<Error>]),
这个感觉可以在 presetPropType 里把类型搞对了。

2024-10-12 08:36 UTC, eternalsky commented on components/time-picker2/time-picker.tsx
> +    clearTimeoutId: NodeJS.Timeout;
应该是 number，以前好像处理过类似问题吧

2024-10-12 08:36 UTC, eternalsky commented on components/time-picker2/time-picker.tsx
> +                  checkRangeDate(formattedValue, state.inputType, disabled)
这感觉应该是修改 checkRangeDate 的类型比较合理。

2024-10-12 08:36 UTC, eternalsky commented on components/time-picker2/time-picker.tsx
> +                value: value as Dayjs,
这里的处理是有 bug 的，应该在这里 expect-error

2024-10-12 08:36 UTC, eternalsky commented on components/time-picker2/time-picker.tsx
> +            (newInputStr as string[])[inputType!] = timeStr;
as string[] 应该放在上一行，还是那个原则，类型越早确定越好，声明时能确定就不要等到使用时再确定

2024-10-12 08:36 UTC, eternalsky commented on components/time-picker2/time-picker.tsx
> +    checkValue: (value: TimePickerProps['value'], strictly?: boolean) => ValueType = (
这里类型声明了两遍

2024-10-12 08:36 UTC, eternalsky commented on components/time-picker2/time-picker.tsx
> +              checkRangeDate(formattedValue, inputType, disabled, strictly)
同上

2024-10-12 08:36 UTC, eternalsky commented on components/time-picker2/time-picker.tsx
> +                        this.onChange(v as ValueType | null);
这里好像不需要额外声明

2024-10-12 08:40 UTC, eternalsky requested changes

2024-10-12 08:40 UTC, eternalsky commented on components/time-picker2/types.ts
> +    disabledHours?: (index?: number) => boolean | number[];
这里感觉应该说明下，目前他在是否 range 的情况下，使用方式是完全不同的，在单选时，是 (index:number) => boolean，在 range 时是 () => number[]; 这个在不说明的情况下感觉很难自己搞明白。

2024-10-12 08:40 UTC, eternalsky commented on components/time-picker2/types.ts
> +    disabledMinutes?: (index?: number) => boolean | number[];
同上

2024-10-12 08:40 UTC, eternalsky commented on components/time-picker2/types.ts
> +    disabledSeconds?: (index?: number) => boolean | number[];
同上

2024-10-14 06:01 UTC, FairyYang commented on components/time-picker2/__docs__/index.en-us.md
> +### 公共 API
公共API是为了和旧文档保持一致，如果不需要这么做的话，就去掉公共部分了

2024-10-15 02:49 UTC, FairyYang commented on components/time-picker2/module/time-menu.tsx
> +        function requestAnimationFrameTimeout(...params: [() => void]) {
从setTImeOut推导出来的

2024-10-15 02:50 UTC, FairyYang commented on components/time-picker2/module/time-menu.tsx
> +        function requestAnimationFrameTimeout(...params: [() => void]) {
![Uploading image.png…]()

2024-10-15 02:50 UTC, FairyYang commented on components/time-picker2/module/time-menu.tsx
> +        function requestAnimationFrameTimeout(...params: [() => void]) {
![image](https://github.com/user-attachments/assets/dd7e5f99-6fb8-44e9-9d3b-6b380e47aad3)

2024-10-15 06:50 UTC, FairyYang commented on components/time-picker2/time-picker.tsx
> +    value: PropTypes.oneOfType([PropTypes.func, checkDateValue as PropTypes.Validator<Error>]),
怎么在presetPropType的类型处理呢，这里的报错是PropTypes.oneOfType的入参类型报错

2024-10-15 06:53 UTC, FairyYang commented on components/time-picker2/time-picker.tsx
> +    clearTimeoutId: NodeJS.Timeout;
哪个应该是number？clearTimeoutId？它是从settimeout推导出来的
![image](https://github.com/user-attachments/assets/8b8d6805-b5ce-4641-91fb-203df188c60b)

2024-10-16 01:37 UTC, eternalsky commented on components/time-picker2/__docs__/demo/preset/index.tsx
> +import dayjs, { type Dayjs } from 'dayjs';
这个 lint 问题看一下

2024-10-16 01:37 UTC, eternalsky commented on components/time-picker2/__docs__/index.en-us.md
> +### TimePicker.RangePicker
RangePicker 的属性显然少了吧

2024-10-16 01:37 UTC, eternalsky commented on components/time-picker2/__docs__/index.en-us.md
> +### 公共 API
> 公共API是为了和旧文档保持一致，如果不需要这么做的话，就去掉公共部分了

旧文档里好像并没有看到公共 API 这个

2024-10-16 03:57 UTC, eternalsky requested changes

2024-10-16 03:57 UTC, eternalsky commented on components/time-picker2/module/date-input.tsx
> +    input: InstanceType<typeof Input> | InstanceType<typeof Input>[] | undefined = undefined;
undefined 有 ? 就可以了，并且可以不明确指定 undefined，不指定就是 undefined

2024-10-16 03:57 UTC, eternalsky commented on components/time-picker2/prop-types.ts
> +                        datejs(v as string | number | Date | Dayjs | null | undefined).isValid() ||
这里还没改

2024-10-16 03:57 UTC, eternalsky commented on components/time-picker2/time-picker.tsx
> +    clearTimeoutId: NodeJS.Timeout;
这个我记得之前的组件里我们有讨论过，可以参考一下其他的组件，window.setTimeout 就可以指向正确的

2024-10-16 03:57 UTC, eternalsky commented on components/time-picker2/time-picker.tsx
> +    value: PropTypes.oneOfType([PropTypes.func, checkDateValue as PropTypes.Validator<Error>]),
> 怎么在presetPropType的类型处理呢，这里的报错是PropTypes.oneOfType的入参类型报错

报错是因为 checkDateValue 的类型不满足 PropTypes.Validator<Error> 的要求，那思路上不是应该把 checkDateValue 的类型改对吗~

2024-10-16 03:57 UTC, eternalsky commented on components/time-picker2/time-picker.tsx
> +                        this.onChange(v as ValueType);
这里好像不需要额外声明

2024-10-16 03:57 UTC, eternalsky commented on components/time-picker2/time-picker.tsx
> +     * @param idx
这个 lint 报错要看一下

2024-10-16 03:57 UTC, eternalsky commented on components/time-picker2/time-picker.tsx
> +interface SharedInputProps extends DateInputProps {
DateInputProps 并不能保证一定是接口，所以这里用 type a = b & {c: xxxx} 更稳定

2024-10-16 03:57 UTC, eternalsky commented on components/time-picker2/time-picker.tsx
> +            disabled: disabled,
这里的修改好像没有意义了

2024-10-16 03:57 UTC, eternalsky commented on components/time-picker2/time-picker.tsx
> +                // @ts-expect-error value 的类型为“ValueType | undefined”，不能分配给类型“Dayjs”。
这类可以 ide 直接提示出来的，没必要写在解释里，解释里应该写的是为什么这里期待会有一个报错，解释的是原因，比如这里是因为 value 确实没有处理是数组的情况。

2024-10-16 03:57 UTC, eternalsky commented on components/time-picker2/time-picker.tsx
> +                value: value,
这里同上

2024-10-16 03:57 UTC, eternalsky commented on components/time-picker2/types.ts
> +     * 禁用小时的函数，当为 range 时，函数需要返回 number[]，非 range 时，返回 boolean
应该写明确，谁哪个属性为 range 时，对用户其实暴露的是 timePicker 和 RangePicker，没有暴露 range 的概念。另外 index 也是非 range 时才有的，这个也应该讲一下

2024-10-17 03:08 UTC, FairyYang commented on components/time-picker2/__docs__/index.en-us.md
> +### TimePicker.RangePicker
![image](https://github.com/user-attachments/assets/25b1bcc7-08bd-45ea-80a3-0806111c1aad)
目前看都是6个

2024-10-17 03:26 UTC, FairyYang commented on components/time-picker2/time-picker.tsx
> +                        this.onChange(v as ValueType);
![image](https://github.com/user-attachments/assets/d155c300-7920-4b8c-b28a-814c878e2fdf)
不声明的话，run check 会报错

2024-10-17 06:40 UTC, eternalsky commented on components/time-picker2/__docs__/index.en-us.md
> +### TimePicker.RangePicker
只有六个，是因为以前有公共 API，如果现在不放公共 API 出来，那么就需要把这部分补齐了。当然保留公共 API 也可以，但是名字上要都能对应上。

2024-10-17 06:56 UTC, eternalsky requested changes

2024-10-17 06:56 UTC, eternalsky commented on components/time-picker2/time-picker.tsx
> +            onKeyDown: this.onKeyDown as unknown as DateInputProps['onKeyDown'],
这里为啥要强制类型转换？

2024-10-17 06:56 UTC, eternalsky commented on components/time-picker2/module/date-input.tsx
> +        // @ts-expect-error 下面 Input 传入 pickProps，不符合 pickProps 的参数类型，导致报错
这里的错误原因应该是由于下方 pickProps 的使用不对，导致返回的结果类型与 InputProps 不匹配。

2024-10-17 06:56 UTC, eternalsky commented on components/time-picker2/time-picker.tsx
> +                        this.onChange(v as ValueType);
那就奇怪了，既然这里只能是 ValueType，那从上面的逻辑里 v 是可以是 string 的。handleChange 里 v 可以是 string 吗？

2024-10-17 09:41 UTC, FairyYang commented
针对最后一个问题的回复：handleChange 里 v 不可以是 string，在VSCODE里，没有as  ValueType，不会报错。

2024-10-18 10:07 UTC, eternalsky requested changes

2024-10-21 03:29 UTC, eternalsky requested changes
LGTM

2024-10-21 03:29 UTC, merged